### ISSUE TITLE
cannot train selsa with different detector

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmtracking#136]
Thanks for the great library.

I want to train selsa with different detector (retinanet for instance) [so I change detector base config to retinanet in the given selsa config](https://github.com/open-mmlab/mmtracking/blob/ecc83b5e6523582b92196095eb21d72d654322f2/configs/vid/selsa/selsa_faster_rcnn_r50_dc5_1x_imagenetvid.py#L2):

```python
_base_ = [
    '../../_base_/models/retinanet_r50_fpn.py',
    '../../_base_/datasets/custom_cocovid_dataset.py',
    '../../_base_/default_runtime.py'
]

model = dict(
    type='SELSA',
    pretrains=None,
    detector=dict(
        roi_head=dict(
            type='SelsaRoIHead',
            bbox_head=dict(
                type='SelsaBBoxHead',
                num_shared_fcs=2,
                aggregator=dict(
                    type='SelsaAggregator',
                    in_channels=1024,
                    num_attention_blocks=16
                ),
                num_classes=1,
            )
        )
    )
)
```

But it gives error:
```
  File "tools/train.py", line 168, in <module>
    main()
  File "tools/train.py", line 141, in main
    model = build_model(cfg.model)
  File "mmtracking\mmtrack\models\builder.py", line 69, in build_model
    return build(cfg, MODELS)
  File "mmtracking\mmtrack\models\builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\FCA\Miniconda3\envs\mmtracking\lib\site-packages\mmcv\utils\registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "mmtracking\mmtrack\models\vid\selsa.py", line 23, in __init__
    self.detector = build_detector(detector)
  File "mmtracking\mmtrack\models\builder.py", line 60, in build_detector
    return build(cfg, DETECTORS)
  File "mmtracking\mmtrack\models\builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\FCA\Miniconda3\envs\mmtracking\lib\site-packages\mmcv\utils\registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'roi_head'
```

What changes should I make to train selsa with other detectors?

**Comment by fcakyon** [comment]
I also tried with this config:

```python
_base_ = [
    '../../_base_/models/retinanet_r50_fpn.py',
    '../../_base_/datasets/custom_cocovid_dataset.py',
    '../../_base_/default_runtime.py'
]

model = dict(
    type='SELSA',
    pretrains=None,
    detector=dict(
        bbox_head=dict(
            type='SelsaBBoxHead',
            num_shared_fcs=2,
            aggregator=dict(
                type='SelsaAggregator',
                in_channels=1024,
                num_attention_blocks=16
            ),
            num_classes=1,
        )
    )
)
```

This time Im getting a different error:
```bash
Traceback (most recent call last):
  File "tools/train.py", line 168, in <module>
    main()
  File "tools/train.py", line 141, in main
    model = build_model(cfg.model)
  File "mmtracking\mmtrack\models\builder.py", line 69, in build_model
    return build(cfg, MODELS)
  File "mmtracking\mmtrack\models\builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\FCA\Miniconda3\envs\mmtracking\lib\site-packages\mmcv\utils\registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "mmtracking\mmtrack\models\vid\selsa.py", line 23, in __init__
    self.detector = build_detector(detector)
  File "mmtracking\mmtrack\models\builder.py", line 60, in build_detector
    return build(cfg, DETECTORS)
  File "mmtracking\mmtrack\models\builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\FCA\Miniconda3\envs\mmtracking\lib\site-packages\mmcv\utils\registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\FCA\Miniconda3\envs\mmtracking\lib\site-packages\mmdet\models\detectors\retinanet.py", line 16, in __init__
    super(RetinaNet, self).__init__(backbone, neck, bbox_head, train_cfg,
  File "C:\Users\FCA\Miniconda3\envs\mmtracking\lib\site-packages\mmdet\models\detectors\single_stage.py", line 30, in __init__        
    self.bbox_head = build_head(bbox_head)
  File "C:\Users\FCA\Miniconda3\envs\mmtracking\lib\site-packages\mmdet\models\builder.py", line 59, in build_head
    return build(cfg, HEADS)
  File "C:\Users\FCA\Miniconda3\envs\mmtracking\lib\site-packages\mmdet\models\builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\FCA\Miniconda3\envs\mmtracking\lib\site-packages\mmcv\utils\registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "mmtracking\mmtrack\models\roi_heads\bbox_heads\selsa_bbox_head.py", line 19, in __init__
    super(SelsaBBoxHead, self).__init__(*args, **kwargs)
  File "C:\Users\FCA\Miniconda3\envs\mmtracking\lib\site-packages\mmdet\models\roi_heads\bbox_heads\convfc_bbox_head.py", line 33, in __init__
    super(ConvFCBBoxHead, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'stacked_convs'
```

**Comment by GT9505** [comment]
[SELSA](https://openaccess.thecvf.com/content_ICCV_2019/papers/Wu_Sequence_Level_Semantics_Aggregation_for_Video_Object_Detection_ICCV_2019_paper.pdf) need aggregate the features of proposals, and RetinaNet doesn't own proposals. Therefore, SELSA cann't be applied into RetinaNet.

**Comment by fcakyon** [comment]
@GT9505 i see. how to train selsa with proposal generating detectors other than fasterrcnn? config stays the same and i only need to change the base model config?

**Comment by GT9505** [comment]
The architecture of second stage in fasterrcnn is `RoI Align -> fc1 -> fc2 -> cls/reg`, and selsa is plugged after each fc (`RoI Align -> fc1 -> selsa -> fc2 -> selsa -> cls/reg`).
Thus, for the image detectors having the similar architecture with fasterrcnn, you just need to modify the base model config. Otherwise, you need change the code.

**Comment by fcakyon** [comment]
@GT9505  thanks for the feedback
