### ISSUE TITLE
Unable to do training and evaluation with new versions of mmdetection

### ISSUE THREAD

**Issue by Cospel** [open-mmlab/mmtracking#175]
**Describe the bug**
After finishing epoch, we are unable to evaluate the SELSA VID model.

**Reproduction**

1. What command or script did you run?

python tools/train.py (with configurations to SELSA models)

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified? No
3. What dataset did you use and what task did you run?

**Environment**

Versions of libs:
- mmdet==2.13.0
- mmcv-full==1.3.5
-
 
**Error traceback**
If applicable, paste the error trackback here.

```none
2021-06-18 15:24:53,793 - mmtrack - INFO - Epoch [1][8400/8403]	lr: 1.000e-02, eta: 3 days, 2:00:01, time: 0.765, data_time: 0.008, memory: 4545, loss_rpn_cls: 0.1214, loss_rpn_bbox: 0.0242, loss_cls: 0.1686, acc: 95.9680, loss_bbox: 0.0485, loss: 0.3626, grad_norm: 0.9721
Traceback (most recent call last):
  File "tools/train.py", line 168, in <module>
    main()
  File "tools/train.py", line 164, in main
    meta=meta)
  File "/home/michal/project/mmtracking/mmtrack/apis/train.py", line 135, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/michal/dev/lib64/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/michal/dev/lib64/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/michal/dev/lib64/python3.6/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/michal/project/mmtracking/mmtrack/core/evaluation/eval_hooks.py", line 12, in after_train_epoch
    if not self.evaluation_flag(runner):
AttributeError: 'EvalHook' object has no attribute 'evaluation_flag'
```

**Bug fix**

I think the problem occurs with new mmdetection 2.13.0: 
https://github.com/open-mmlab/mmdetection/commit/9e79adab2268c281036a4625ad57db224de8a35e

**Comment by ToumaKazusa3** [comment]
hi~ you can try to install mmdet=2.12.0 or recompile mmdet and mmtrack from source.
