### ISSUE TITLE
when I try to run train.py ,there is a error which RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by ilmoney** [open-mmlab/mmtracking#297]
This problem has bothered me for a long time. 
The specific error is this：
Traceback (most recent call last):
  File "tools/train.py", line 192, in <module>
    main()
  File "tools/train.py", line 166, in main
    model.init_weights()
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 106, in init_weights
    initialize(self, self.init_cfg)
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/mmcv/cnn/utils/weight_init.py", line 612, in initialize
    _initialize(module, cp_cfg)
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/mmcv/cnn/utils/weight_init.py", line 517, in _initialize
    func(module)
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/mmcv/cnn/utils/weight_init.py", line 494, in __call__
    logger=logger)
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 513, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 371, in load_from_torchvision
    return load_from_http(model_urls[model_name], map_location=map_location)
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 284, in load_from_http
    filename, model_dir=model_dir, map_location=map_location)
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/torch/hub.py", line 575, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/environment/python/versions/miniconda3-4.7.12/envs/mymmlab/lib/python3.7/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

i think there are problems in weights file ，but i have download .pth in checkpoints file ,i can not solve it .
please help me 
I executed this command 
 python tools/train.py configs/vid/temporal_roi_align/selsa_troialign_faster_rcnn_r101_dc5_7e_imagenetvid.py

**Comment by ilmoney** [comment]
pyhtorch 1.9 和cuda11.1 
resnext101_64x4d-ee2c6f71.pth

**Comment by GT9505** [comment]
> I also encountered a problem recently： RuntimeError: cannot reshape tensor of 0 elements into shape [0, 16, -1] because the unspecified dimension size -1 can be any value and is ambiguous this is datasets problem？
Could you use the [template of error-reported](https://github.com/open-mmlab/mmtracking/blob/master/.github/ISSUE_TEMPLATE/error-report.md) to report the bug.
It is hard to provide useful help without the full error information.
