### ISSUE TITLE
ImageNet VID IndexError: list index out of range in coco.py line 190

### ISSUE THREAD

**Issue by zpyi** [open-mmlab/mmtracking#325]
I have converted ImageNet VID datasets as tutorials, but when I evaluate vid models(such as selsa), it throws this error. 
I evaluate on a small dataset(correct CocoVideoDataset format) , it reported as below:

load checkpoint from local path: ./work_dirs/selsapa_faster_rcnn_r50_dc5_1x_vis/epoch_1.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2846/2846, 3.7 task/s, elapsed: 777s, ETA:     0sTraceback (most recent call last):
  File "./tools/test.py", line 208, in <module>
    main()
  File "./tools/test.py", line 198, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/home/zh/mmdetection/mmtracking/mmtrack/datasets/coco_video_dataset.py", line 448, in evaluate
    **bbox_kwargs)
  File "/home/zh/mmdetection/mmdet/datasets/coco.py", line 359, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/home/zh/mmdetection/mmdet/datasets/coco.py", line 320, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/home/zh/mmdetection/mmdet/datasets/coco.py", line 253, in results2json
    json_results = self._det2json(results)
  File "/home/zh/mmdetection/mmdet/datasets/coco.py", line 190, in _det2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range
/home/zh/miniconda3/envs/mmtrack/lib/python3.7/tempfile.py:798: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpsfzy7if0'>
  _warnings.warn(warn_message, ResourceWarning)

**Comment by zpyi** [comment]
Besides, the "val tqdm" always stopped at 130968/176126, and the error above was reported.

**Comment by zpyi** [comment]
Besides, the "val tqdm" always stopped at 130968/176126, and the error above was reported. The training process can run normally.

**Comment by zpyi** [comment]
I evaluate on a small dataset , it reported as below:

load checkpoint from local path: ./work_dirs/selsapa_faster_rcnn_r50_dc5_1x_vis/epoch_1.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2846/2846, 3.7 task/s, elapsed: 777s, ETA:     0sTraceback (most recent call last):
  File "./tools/test.py", line 208, in <module>
    main()
  File "./tools/test.py", line 198, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/home/zh/mmdetection/mmtracking/mmtrack/datasets/coco_video_dataset.py", line 448, in evaluate
    **bbox_kwargs)
  File "/home/zh/mmdetection/mmdet/datasets/coco.py", line 359, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/home/zh/mmdetection/mmdet/datasets/coco.py", line 320, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/home/zh/mmdetection/mmdet/datasets/coco.py", line 253, in results2json
    json_results = self._det2json(results)
  File "/home/zh/mmdetection/mmdet/datasets/coco.py", line 190, in _det2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range
/home/zh/miniconda3/envs/mmtrack/lib/python3.7/tempfile.py:798: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpsfzy7if0'>
  _warnings.warn(warn_message, ResourceWarning)

**Comment by GT9505** [comment]
Please use [error-report.md](https://github.com/open-mmlab/mmtracking/blob/master/.github/ISSUE_TEMPLATE/error-report.md) to report error
