### ISSUE TITLE
NotImplementedError: Not supported YouTubeVIS datasetversion: data

### ISSUE THREAD

**Issue by abby-coco** [open-mmlab/mmtracking#330]
Traceback (most recent call last):
  File "/home1/lyr2/anaconda3/envs/mmtrack2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home1/lyr2/CODE/mmtracking-master/mmtrack/datasets/youtube_vis_dataset.py", line 40, in __init__
    self.set_dataset_classes(dataset_version)
  File "/home1/lyr2/CODE/mmtracking-master/mmtrack/datasets/youtube_vis_dataset.py", line 50, in set_dataset_classes
    raise NotImplementedError('Not supported YouTubeVIS dataset'
NotImplementedError: Not supported YouTubeVIS datasetversion: data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 206, in <module>
    main()
  File "tools/test.py", line 132, in main
    dataset = build_dataset(cfg.data.test)
  File "/home1/lyr2/anaconda3/envs/mmtrack2/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 80, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home1/lyr2/anaconda3/envs/mmtrack2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
NotImplementedError: YouTubeVISDataset: Not supported YouTubeVIS datasetversion: data

**Comment by GT9505** [comment]
The [code](https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/datasets/youtube_vis_dataset.py#L44) in youtubevis dataset shows that the option of `dataset_version` is `2019` or `2021`, which means `YouTubeVIS-2019` or `YouTubeVIS-2019` dataset.
