### ISSUE TITLE
Proposal error with custom neck

### ISSUE THREAD

**Issue by Chop1** [open-mmlab/mmtracking#370]
I modified the neck and got correct output shape from it.

However when training MS ROI align I got an error after a while. It work for several steps, then the number of proposal suddenly drop to 2 for the target frame and 0 for support frames.

I did some print:

steps where it works:
```python
# neck ouput
outputs[0].shape = torch.Size([3, 64, 152, 180])
outputs[1].shape = torch.Size([3, 64, 76, 90])
outputs[2].shape = torch.Size([3, 64, 38, 45])
outputs[3].shape = torch.Size([3, 64, 19, 23])
outputs[4].shape = torch.Size([3, 64, 10, 12])

num sampling results: 1, num ref_proposal_list: 2
sampling result: 512
ref_proposal: torch.Size([1000, 5])
ref_proposal: torch.Size([1000, 5])
_bbox_forward_train | rois: torch.Size([512, 5]), ref_rois: torch.Size([2000, 5])
_bbox_forward | rois: torch.Size([512, 5]), ref_rois: torch.Size([2000, 5])
_bbox_forward | x: torch.Size([1, 64, 152, 180]),	ref_x: torch.Size([2, 64, 152, 180])
_bbox_forward | x: torch.Size([1, 64, 76, 90]),	ref_x: torch.Size([2, 64, 76, 90])
_bbox_forward | x: torch.Size([1, 64, 38, 45]),	ref_x: torch.Size([2, 64, 38, 45])
_bbox_forward | x: torch.Size([1, 64, 19, 23]),	ref_x: torch.Size([2, 64, 19, 23])
_bbox_forward | x: torch.Size([1, 64, 10, 12]),	ref_x: torch.Size([2, 64, 10, 12])
most_similar_roi_align forward | rois: torch.Size([512, 5])
most_similar_roi_align forward | feats: torch.Size([1, 64, 152, 180])
most_similar_roi_align forward | feats: torch.Size([1, 64, 76, 90])
most_similar_roi_align forward | feats: torch.Size([1, 64, 38, 45])
most_similar_roi_align forward | feats: torch.Size([1, 64, 19, 23])
most_similar_roi_align | roi_feats: torch.Size([512, 64, 7, 7]), ref_feats: torch.Size([2, 64, 19, 23])
temporal_attentional_feature_aggregation | x: torch.Size([1, 512, 64, 7, 7]), ref_x: torch.Size([2, 512, 64, 7, 7])
bbox_feats: torch.Size([512, 64, 7, 7])
most_similar_roi_align forward | rois: torch.Size([2000, 5])
most_similar_roi_align forward | feats: torch.Size([2, 64, 152, 180])
most_similar_roi_align forward | feats: torch.Size([2, 64, 76, 90])
most_similar_roi_align forward | feats: torch.Size([2, 64, 38, 45])
most_similar_roi_align forward | feats: torch.Size([2, 64, 19, 23])
SelsaBBoxHead | x: torch.Size([512, 64, 7, 7]), ref_x: torch.Size([2000, 64, 7, 7])
x: torch.Size([512, 512]), ref_x: torch.Size([2000, 512])
x: torch.Size([512, 512]), ref_x: torch.Size([2000, 512])
x: torch.Size([512, 512]), ref_x: torch.Size([2000, 512])
```

then I got this and it crash, due to no proposals

```python
outputs[0].shape = torch.Size([3, 64, 136, 252])
outputs[1].shape = torch.Size([3, 64, 68, 126])
outputs[2].shape = torch.Size([3, 64, 34, 63])
outputs[3].shape = torch.Size([3, 64, 17, 32])
outputs[4].shape = torch.Size([3, 64, 9, 16])


### Here got only 2 ROIs from target proposals and 0 for each ref, while before I go 512 for target and 1000 for each proposals
num sampling results: 1, num ref_proposal_list: 2
sampling result: 2
ref_proposal: torch.Size([0, 5])
ref_proposal: torch.Size([0, 5])


_bbox_forward_train | rois: torch.Size([2, 5]), ref_rois: torch.Size([0, 5])
_bbox_forward | rois: torch.Size([2, 5]), ref_rois: torch.Size([0, 5])
_bbox_forward | x: torch.Size([1, 64, 136, 252]),	ref_x: torch.Size([2, 64, 136, 252])
_bbox_forward | x: torch.Size([1, 64, 68, 126]),	ref_x: torch.Size([2, 64, 68, 126])
_bbox_forward | x: torch.Size([1, 64, 34, 63]),	ref_x: torch.Size([2, 64, 34, 63])
_bbox_forward | x: torch.Size([1, 64, 17, 32]),	ref_x: torch.Size([2, 64, 17, 32])
_bbox_forward | x: torch.Size([1, 64, 9, 16]),	ref_x: torch.Size([2, 64, 9, 16])
most_similar_roi_align forward | rois: torch.Size([2, 5])
most_similar_roi_align forward | feats: torch.Size([1, 64, 136, 252])
most_similar_roi_align forward | feats: torch.Size([1, 64, 68, 126])
most_similar_roi_align forward | feats: torch.Size([1, 64, 34, 63])
most_similar_roi_align forward | feats: torch.Size([1, 64, 17, 32])
most_similar_roi_align | roi_feats: torch.Size([2, 64, 7, 7]), ref_feats: torch.Size([2, 64, 17, 32])
temporal_attentional_feature_aggregation | x: torch.Size([1, 2, 64, 7, 7]), ref_x: torch.Size([2, 2, 64, 7, 7])
bbox_feats: torch.Size([2, 64, 7, 7])
most_similar_roi_align forward | rois: torch.Size([0, 5])
most_similar_roi_align forward | feats: torch.Size([2, 64, 136, 252])
most_similar_roi_align forward | feats: torch.Size([2, 64, 68, 126])
most_similar_roi_align forward | feats: torch.Size([2, 64, 34, 63])
most_similar_roi_align forward | feats: torch.Size([2, 64, 17, 32])
SelsaBBoxHead | x: torch.Size([2, 64, 7, 7]), ref_x: torch.Size([0, 64, 7, 7])
x: torch.Size([2, 512]), ref_x: torch.Size([0, 512])
Traceback (most recent call last):
  File "./tools/train.py", line 175, in <module>
    main()
  File "./tools/train.py", line 171, in main
    meta=meta)
  File "/home/apeus/Adrien/mmtracking/mmtrack/apis/train.py", line 137, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/apeus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/apeus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/apeus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/apeus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/apeus/Adrien/mmtracking/mmtrack/models/vid/base.py", line 265, in train_step
    losses = self(**data)
  File "/home/apeus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/apeus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/apeus/Adrien/mmtracking/mmtrack/models/vid/base.py", line 194, in forward
    **kwargs)
  File "/home/apeus/Adrien/mmtracking/mmtrack/models/vid/selsa.py", line 166, in forward_train
    gt_labels, gt_bboxes_ignore, gt_masks, **kwargs)
  File "/home/apeus/Adrien/mmtracking/mmtrack/models/roi_heads/selsa_roi_head.py", line 69, in forward_train
    gt_bboxes, gt_labels)
  File "/home/apeus/Adrien/mmtracking/mmtrack/models/roi_heads/selsa_roi_head.py", line 124, in _bbox_forward_train
    bbox_results = self._bbox_forward(x, ref_x, rois, ref_rois)
  File "/home/apeus/Adrien/mmtracking/mmtrack/models/roi_heads/selsa_roi_head.py", line 103, in _bbox_forward
    cls_score, bbox_pred = self.bbox_head(bbox_feats, ref_bbox_feats)
  File "/home/apeus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/apeus/Adrien/mmtracking/mmtrack/models/roi_heads/bbox_heads/selsa_bbox_head.py", line 60, in forward
    x = x + self.aggregator[i](x, ref_x)
  File "/home/apeus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/apeus/Adrien/mmtracking/mmtrack/models/aggregators/selsa_aggregator.py", line 65, in forward
    -1).permute(1, 2, 0)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 2, -1] because the unspecified dimension size -1 can be any value and is ambiguous

```

**Comment by GT9505** [comment]
please refer to [this comment](https://github.com/open-mmlab/mmtracking/issues/297#issuecomment-949423184) to solve the bug.

**Comment by Chop1** [comment]
While adding this fix the crash, it cause the loss to go to NaN.

```python
2021-12-17 10:10:05,402 - mmtrack - INFO - Epoch [1][50/8262]	lr: 1.993e-03, eta: 8:34:45, time: 0.624, data_time: 0.475, memory: 1963, loss_rpn_cls: 0.6450, loss_rpn_bbox: 0.0094, loss_cls: 0.1858, acc: 97.0380, loss_bbox: 0.0455, loss: 0.8856, grad_norm: 1.7260
2021-12-17 10:10:12,613 - mmtrack - INFO - Epoch [1][100/8262]	lr: 2.327e-03, eta: 5:16:34, time: 0.144, data_time: 0.006, memory: 1963, loss_rpn_cls: 0.2374, loss_rpn_bbox: 0.0100, loss_cls: 0.1172, acc: 97.2907, loss_bbox: 0.0634, loss: 0.4281, grad_norm: 1.7953
2021-12-17 10:10:19,898 - mmtrack - INFO - Epoch [1][150/8262]	lr: 2.660e-03, eta: 4:10:50, time: 0.146, data_time: 0.007, memory: 1963, loss_rpn_cls: 0.0609, loss_rpn_bbox: 0.0091, loss_cls: 0.1462, acc: 96.3915, loss_bbox: 0.0905, loss: 0.3067, grad_norm: 1.2621
2021-12-17 10:10:27,147 - mmtrack - INFO - Epoch [1][200/8262]	lr: 2.993e-03, eta: 3:37:44, time: 0.145, data_time: 0.006, memory: 1963, loss_rpn_cls: 0.0499, loss_rpn_bbox: 0.0094, loss_cls: 0.1542, acc: 96.1087, loss_bbox: 0.0975, loss: 0.3111, grad_norm: 1.1253
2021-12-17 10:10:34,488 - mmtrack - INFO - Epoch [1][250/8262]	lr: 3.327e-03, eta: 3:18:10, time: 0.147, data_time: 0.006, memory: 1963, loss_rpn_cls: 0.0490, loss_rpn_bbox: 0.0099, loss_cls: 0.1605, acc: 95.7618, loss_bbox: 0.1027, loss: 0.3220, grad_norm: 1.1291
2021-12-17 10:10:41,775 - mmtrack - INFO - Epoch [1][300/8262]	lr: 3.660e-03, eta: 3:04:55, time: 0.146, data_time: 0.007, memory: 1963, loss_rpn_cls: 0.0437, loss_rpn_bbox: 0.0084, loss_cls: 0.1592, acc: 95.7177, loss_bbox: 0.1010, loss: 0.3123, grad_norm: 1.0838
2021-12-17 10:10:49,065 - mmtrack - INFO - Epoch [1][350/8262]	lr: 3.993e-03, eta: 2:55:25, time: 0.146, data_time: 0.006, memory: 1963, loss_rpn_cls: 0.0439, loss_rpn_bbox: 0.0086, loss_cls: 0.1654, acc: 95.4017, loss_bbox: 0.1058, loss: 0.3237, grad_norm: 1.3064
2021-12-17 10:10:55,956 - mmtrack - INFO - Epoch [1][400/8262]	lr: 4.327e-03, eta: 2:47:27, time: 0.138, data_time: 0.006, memory: 1963, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 75.6016, loss_bbox: nan, loss: nan, grad_norm: nan
2021-12-17 10:11:02,453 - mmtrack - INFO - Epoch [1][450/8262]	lr: 4.660e-03, eta: 2:40:31, time: 0.130, data_time: 0.006, memory: 1963, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 39.7500, loss_bbox: nan, loss: nan, grad_norm: nan
2021-12-17 10:11:08,921 - mmtrack - INFO - Epoch [1][500/8262]	lr: 4.993e-03, eta: 2:34:54, time: 0.129, data_time: 0.006, memory: 1963, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 45.1667, loss_bbox: nan, loss: nan, grad_norm: nan
2021-12-17 10:11:15,346 - mmtrack - INFO - Epoch [1][550/8262]	lr: 5.000e-03, eta: 2:30:13, time: 0.128, data_time: 0.006, memory: 1963, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 45.6667, loss_bbox: nan, loss: nan, grad_norm: nan
2021-12-17 10:11:21,881 - mmtrack - INFO - Epoch [1][600/8262]	lr: 5.000e-03, eta: 2:26:27, time: 0.131, data_time: 0.006, memory: 1963, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 48.8333, loss_bbox: nan, loss: nan, grad_norm: nan
2021-12-17 10:11:28,470 - mmtrack - INFO - Epoch [1][650/8262]	lr: 5.000e-03, eta: 2:23:18, time: 0.132, data_time: 0.006, memory: 1963, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 44.5833, loss_bbox: nan, loss: nan, grad_norm: nan
```

I'm not sure to understand what is happening. The number of proposal is fixed, obtained by ranking the proposal and selecting the top performers. It makes no sense to obtain 0 proposals ? This issue does not seems to be related to VID nature of the model.

**Comment by GT9505** [comment]
I agree with you that it is impossible to obtain 0 proposals. It is weird.

Could you find the target frame that only generates 2 proposals, and see whether there is a problem with the input data?
