### ISSUE TITLE
my config is：tracktor_faster-rcnn_r50_fpn_4e_mot17-public.py，but there is a traceback:TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by sweetboxwwy** [open-mmlab/mmtracking#374]
Traceback (most recent call last):
  File "E:/PycharmProjects/GitHubProjects/mmtracking-master/mmtracking-master/tools/train.py", line 181, in <module>
    main()
  File "E:/PycharmProjects/GitHubProjects/mmtracking-master/mmtracking-master/tools/train.py", line 178, in main
    meta=meta)
  File "E:\PycharmProjects\GitHubProjects\mmtracking-master\mmtracking-master\tools\mmtrack\apis\train.py", line 175, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\wangwy\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\wangwy\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\wangwy\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\wangwy\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\wangwy\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects

**Comment by GT9505** [comment]
Please refer to [this](https://github.com/open-mmlab/mmtracking/tree/master/configs/mot#training-with-mot-configs) for the training of Tracktor.
