### ISSUE TITLE
KeyError: "YouTubeVISDataset: 'image_id'"

### ISSUE THREAD

**Issue by hammerAttack** [open-mmlab/mmtracking#380]
There is no ImageID attribute name in the annotation of YouTube vis dataset. How to solve this problem?please...

/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/pycocotools/coco.py:84: ResourceWarning: unclosed file <_io.TextIOWrapper name='data/youtube_vis_2021/annotations/youtube_vis_2021_train.json' mode='r' encoding='UTF-8'>
dataset = json.load(open(annotation_file, 'r'))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Done (t=9.76s)
creating index...
Traceback (most recent call last):
File "/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
return obj_cls(**args)
File "/home/hello1/桌面/lcz_file/mmtracking/mmtrack/datasets/youtube_vis_dataset.py", line 42, in init
super().init(*args, **kwargs)
File "/home/hello1/桌面/lcz_file/mmtracking/mmtrack/datasets/coco_video_dataset.py", line 46, in init
super().init(*args, **kwargs)
File "/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 92, in init
self.data_infos = self.load_annotations(local_path)
File "/home/hello1/桌面/lcz_file/mmtracking/mmtrack/datasets/coco_video_dataset.py", line 61, in load_annotations
data_infos = self.load_video_anns(ann_file)
File "/home/hello1/桌面/lcz_file/mmtracking/mmtrack/datasets/coco_video_dataset.py", line 73, in load_video_anns
self.coco = CocoVID(ann_file)
File "/home/hello1/桌面/lcz_file/mmtracking/mmtrack/datasets/parsers/coco_video_parser.py", line 22, in init
super(CocoVID, self).init(annotation_file=annotation_file)
File "/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/mmdet/datasets/api_wrappers/coco_api.py", line 23, in init
super().init(annotation_file=annotation_file)
File "/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/pycocotools/coco.py", line 88, in init
self.createIndex()
File "/home/hello1/桌面/lcz_file/mmtracking/mmtrack/datasets/parsers/coco_video_parser.py", line 57, in createIndex
imgToAnns[ann['image_id']].append(ann)
KeyError: 'image_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "tools/train.py", line 183, in
main()
File "tools/train.py", line 158, in main
datasets = [build_dataset(cfg.data.train)]
File "/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 81, in build_dataset
dataset = build_from_cfg(cfg, DATASETS, default_args)
File "/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
raise type(e)(f'{obj_cls.name}: {e}')
KeyError: "YouTubeVISDataset: 'image_id'"

**Comment by hammerAttack** [comment]
/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/pycocotools/coco.py:84: ResourceWarning: unclosed file <_io.TextIOWrapper name='data/youtube_vis_2021/annotations/youtube_vis_2021_train.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Done (t=9.76s)
creating index...
Traceback (most recent call last):
  File "/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/hello1/桌面/lcz_file/mmtracking/mmtrack/datasets/youtube_vis_dataset.py", line 42, in __init__
    super().__init__(*args, **kwargs)
  File "/home/hello1/桌面/lcz_file/mmtracking/mmtrack/datasets/coco_video_dataset.py", line 46, in __init__
    super().__init__(*args, **kwargs)
  File "/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 92, in __init__
    self.data_infos = self.load_annotations(local_path)
  File "/home/hello1/桌面/lcz_file/mmtracking/mmtrack/datasets/coco_video_dataset.py", line 61, in load_annotations
    data_infos = self.load_video_anns(ann_file)
  File "/home/hello1/桌面/lcz_file/mmtracking/mmtrack/datasets/coco_video_dataset.py", line 73, in load_video_anns
    self.coco = CocoVID(ann_file)
  File "/home/hello1/桌面/lcz_file/mmtracking/mmtrack/datasets/parsers/coco_video_parser.py", line 22, in __init__
    super(CocoVID, self).__init__(annotation_file=annotation_file)
  File "/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/mmdet/datasets/api_wrappers/coco_api.py", line 23, in __init__
    super().__init__(annotation_file=annotation_file)
  File "/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/pycocotools/coco.py", line 88, in __init__
    self.createIndex()
  File "/home/hello1/桌面/lcz_file/mmtracking/mmtrack/datasets/parsers/coco_video_parser.py", line 57, in createIndex
    imgToAnns[ann['image_id']].append(ann)
KeyError: 'image_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 183, in <module>
    main()
  File "tools/train.py", line 158, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 81, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/hello/anaconda3/envs/vistr/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "YouTubeVISDataset: 'image_id'"

**Comment by GT9505** [comment]
Did you follow [`dataset.md`](https://github.com/open-mmlab/mmtracking/blob/master/docs/en/dataset.md) to prepare the YouTube-VIS dataset?

**Comment by hammerAttack** [comment]
Oh, I was negligent. Thank you very much for your answer. It's really helpful to me.

**Comment by hammerAttack** [comment]
> 你关注了吗 [`dataset.md`](https://github.com/open-mmlab/mmtracking/blob/master/docs/en/dataset.md#14-video-instance-segmentation)准备 YouTube-VIS 数据集？
Oh, I was negligent. Thank you very much for your answer. It's really helpful to me.

**Comment by hammerAttack** [comment]
> 你关注了吗 [`dataset.md`](https://github.com/open-mmlab/mmtracking/blob/master/docs/en/dataset.md#14-video-instance-segmentation)准备 YouTube-VIS 数据集？

Oh, I was negligent. Thank you very much for your answer. It's really helpful to me.

**Comment by eatbreakfast111** [comment]
> > 你关注了吗 [`dataset.md`](https://github.com/open-mmlab/mmtracking/blob/master/docs/en/dataset.md#14-video-instance-segmentation)准备 YouTube-VIS 数据集？
> 
> Oh, I was negligent. Thank you very much for your answer. It's really helpful to me.

Hello, could you please tell me how to fix this problem?
