### ISSUE TITLE
AttributeError: 'List' object has no attribute '_readonly'

### ISSUE THREAD

**Issue by Tyushang** [open-mmlab/mmtracking#416]
I get started by https://mmtracking.readthedocs.io/en/latest/install.html
But when I run demo, I got the following error:
```shell
(mmtracking) lmd@lmd-four:~/opensource/mmtracking$ python demo/demo_mot_vis.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4
Traceback (most recent call last):
  File "demo/demo_mot_vis.py", line 9, in <module>
    from mmtrack.apis import inference_mot, init_model
  File "/home/lmd/opensource/mmtracking/mmtrack/apis/__init__.py", line 2, in <module>
    from .inference import inference_mot, inference_sot, inference_vid, init_model
  File "/home/lmd/opensource/mmtracking/mmtrack/apis/inference.py", line 10, in <module>
    from mmtrack.models import build_model
  File "/home/lmd/opensource/mmtracking/mmtrack/models/__init__.py", line 8, in <module>
    from .mot import *  # noqa: F401,F403
  File "/home/lmd/opensource/mmtracking/mmtrack/models/mot/__init__.py", line 2, in <module>
    from .base import BaseMultiObjectTracker
  File "/home/lmd/opensource/mmtracking/mmtrack/models/mot/base.py", line 10, in <module>
    from mmtrack.core import imshow_tracks, results2outs
  File "/home/lmd/opensource/mmtracking/mmtrack/core/__init__.py", line 4, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/home/lmd/opensource/mmtracking/mmtrack/core/evaluation/__init__.py", line 5, in <module>
    from .eval_sot_vot import (bbox2region, eval_sot_accuracy_robustness,
  File "/home/lmd/opensource/mmtracking/mmtrack/core/evaluation/eval_sot_vot.py", line 7, in <module>
    from vot.analysis import is_special
  File "/data/anaconda3/envs/mmtracking/lib/python3.7/site-packages/vot/analysis/__init__.py", line 19, in <module>
    from vot.experiment import Experiment
  File "/data/anaconda3/envs/mmtracking/lib/python3.7/site-packages/vot/experiment/__init__.py", line 65, in <module>
    class Experiment(Attributee):
  File "/data/anaconda3/envs/mmtracking/lib/python3.7/site-packages/vot/experiment/__init__.py", line 70, in Experiment
    transformers = List(Object(transformer_resolver), default=[])
  File "/data/anaconda3/envs/mmtracking/lib/python3.7/site-packages/attributee/containers.py", line 124, in __init__
    super().__init__(**kwargs)
  File "/data/anaconda3/envs/mmtracking/lib/python3.7/site-packages/attributee/__init__.py", line 64, in __init__
    self._default = default if is_undefined(default) else (None if default is None else self.coerce(default, CoerceContext()))
  File "/data/anaconda3/envs/mmtracking/lib/python3.7/site-packages/attributee/containers.py", line 135, in coerce
    if self.readonly:
  File "/data/anaconda3/envs/mmtracking/lib/python3.7/site-packages/attributee/__init__.py", line 84, in readonly
    return self._readonly
AttributeError: 'List' object has no attribute '_readonly'
```

2. No modification made;
3. No dataset used;

**Bug fix**
I find that the latest version(0.1.6) of "attributee" is not compatible with mmtrancking master branch by now.  I turned "attributee" back to version 0.1.3, and it worked well.
So could you 'pip freeze' to some txt, let us know which version of packages will work.

**Comment by JingweiZhang12** [comment]
Thanks for your feedback. We have fixed it in `https://github.com/open-mmlab/mmtracking/commit/ccaaab2a8ce95f4103c555a48d173aff2789ade7`

**Comment by zhixuanli** [comment]
@JingweiZhang12 Thanks a lot!
```pip install attributee==0.1.5```
