### ISSUE TITLE
Exception has occurred: FileNotFoundError file "./configs/mot/bytetrack/bytetrack_yolox_x_mot17-private-half.py" does not exist

### ISSUE THREAD

**Issue by ZihaoZhao** [open-mmlab/mmtracking#431]
**Describe the bug**

Exception has occurred: FileNotFoundError file "./configs/mot/bytetrack/bytetrack_yolox_x_mot17-private-half.py" does not exist

**Reproduction**

1. What command or script did you run?

```none
tools/test.py /zhzhao/code/mmtracking/configs/mot/bytetrack/bytetrack_yolox_x_crowdhuman_mot20-private-half.py --eval track
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No modifications

3. What dataset did you use and what task did you run?
MOT20 Bytetrack

**Environment**

```none
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.5.5
MMCV: 1.4.4
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMTracking: 0.10.0+922b5ca
```

**Error traceback**
If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/zhzhao/code/mmtracking/tools/test.py", line 233, in <module>
    main()
  File "/zhzhao/code/mmtracking/tools/test.py", line 103, in main
    cfg = Config.fromfile(args.config)
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/config.py", line 335, in fromfile
    use_predefined_variables)
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/config.py", line 248, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/config.py", line 181, in _file2dict
    check_file_exist(filename)
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/zhzhao/code/mmtracking/configs/mot/bytetrack/bytetrack_yolox_x_mot17-private-half.py" does not exist
```

**Bug fix**
I find _base_ = ['./bytetrack_yolox_x_mot17-private-half.py'] in the config file, so I change it to the existing file "configs/mot/bytetrack/bytetrack_yolox_x_crowdhuman_mot17-private-half.py". However I this error.

```none
Traceback (most recent call last):
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/zhzhao/code/mmtracking/mmtrack/datasets/mot_challenge_dataset.py", line 42, in __init__
    super().__init__(*args, **kwargs)
  File "/zhzhao/code/mmtracking/mmtrack/datasets/coco_video_dataset.py", line 46, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'test_pipeline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/zhzhao/code/mmtracking/tools/test.py", line 233, in <module>
    main()
  File "/zhzhao/code/mmtracking/tools/test.py", line 153, in main
    dataset = build_dataset(cfg.data.test)
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 81, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/zhzhao/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: MOTChallengeDataset: __init__() got an unexpected keyword argument 'test_pipeline'
```

**Comment by Seerkfang** [comment]
Thank you for pointing out this error, we will modify the base config name and pipeline name soon. You can pull the mater later or simply change the key from 'test_pipeline' to 'pipeline' in lines 69 and 73 of 'bytetrack_yolox_x_crowdhuman_mot20-private-half.py'.
