### ISSUE TITLE
When I try to train ILSVRC2015 dataset using FGFA for vid task, after modifying workflow=[('train', 1)] to workflow=[('train', 1), ('val', 1)] in config , will produce this error, I made sure I have modified the pipeline, but it still produces this error, if I remove ('val', 1), it works fine

### ISSUE THREAD

**Issue by Hikar1i** [open-mmlab/mmtracking#464]
When I try to train ILSVRC2015 dataset using FGFA for vid task, after modifying workflow=[('train', 1)] to workflow=[('train', 1), ('val', 1)] in config , will produce this error, I made sure I have modified the pipeline, but it still produces this error, if I remove ('val', 1), it works fine
我尝试使用FGFA进行vid任务训练ILSVRC2015数据集时，在config中将workflow = [('train', 1)]修改为workflow=[('train', 1), ('val', 1)]后，会产生这个错误，我确保已经修改了pipeline，但是还是会产生此错误，如果删除('val', 1)，就可以正常运行

Traceback (most recent call last):
  File "tools/train.py", line 184, in <module>
    main()
  File "tools/train.py", line 180, in main
    meta=meta)
  File "/home/whj/anaconda3/envs/chen/lib/python3.6/site-packages/mmtrack/apis/train.py", line 62, in train_model
    seed=cfg.seed) for ds in dataset
  File "/home/whj/anaconda3/envs/chen/lib/python3.6/site-packages/mmtrack/apis/train.py", line 62, in <listcomp>
    seed=cfg.seed) for ds in dataset
  File "/home/whj/anaconda3/envs/chen/lib/python3.6/site-packages/mmtrack/datasets/builder.py", line 58, in build_dataloader
    sampler = GroupSampler(dataset, samples_per_gpu) if shuffle else None
  File "/home/whj/anaconda3/envs/chen/lib/python3.6/site-packages/mmdet/datasets/samplers/group_sampler.py", line 20, in __init__
    self.flag = dataset.flag.astype(np.int64)
AttributeError: 'ImagenetVIDDataset' object has no attribute 'flag'

**Comment by JingweiZhang12** [comment]
Thanks for your pointing out. It's a potential bug. The error is rooted in https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/custom.py#L120.  

You can add a line code before [this](https://github.com/open-mmlab/mmtracking/blob/96f7f9f6a5/tools/train.py#L189) to fix it:
`val_dataset.test_mode = False`

We'll appreciate it if you can create a PR to fix this bug.

BTW, please note that the `val`  in the `workflow` does not mean the true evaluation on the validate set. It's only used to check some metrics about the model on the validate set.  Details can be seen [this](https://github.com/open-mmlab/mmtracking/blob/96f7f9f6a5/docs/en/tutorials/customize_runtime.md).
We usually use the eval hook to evaluate the method on the `val` dataset.
