### ISSUE TITLE
test SORT

### ISSUE THREAD

**Issue by csdingithub** [open-mmlab/mmtracking#467]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use and what task did you run?

**Environment**

1. Please run `python mmtrack/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by csdingithub** [comment]
**Error trackback:**
```bash
Evaluate CLEAR MOT results.
Traceback (most recent call last):
  File "./tools/test.py", line 225, in <module>
    main()
  File "./tools/test.py", line 215, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/remote-home/chenshaodong/Code/mmtracking/mmtrack/datasets/mot_challenge_dataset.py", line 393, in evaluate
    generate_overall=True)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/motmetrics/metrics.py", line 285, in compute_many
    for acc, analysis, name in zip(dfs, anas, names)]
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/motmetrics/metrics.py", line 285, in <listcomp>
    for acc, analysis, name in zip(dfs, anas, names)]
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/motmetrics/metrics.py", line 185, in compute
    cache[mname] = self._compute(df_map, mname, cache, options, parent='summarize')
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/motmetrics/metrics.py", line 310, in _compute
    v = cache[depname] = self._compute(df_map, depname, cache, options, parent=name)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/motmetrics/metrics.py", line 310, in _compute
    v = cache[depname] = self._compute(df_map, depname, cache, options, parent=name)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/motmetrics/metrics.py", line 315, in _compute
    return minfo['fnc'](df_map, *vals, **options)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/motmetrics/metrics.py", line 610, in id_global_assignment
    fnmatrix = np.full((no + nh, no + nh), 0.)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numpy/core/numeric.py", line 343, in full
    a = empty(shape, dtype, order)
numpy.core._exceptions.MemoryError: Unable to allocate 1.70 GiB for an array with shape (15106, 15106) and data type float64
Traceback (most recent call last):
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/test.py', '--local_rank=0', './configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py', '--launcher', 'pytorch', '--eval', 'track', '--out', '/remote-home/chenshaodong/Code/mmtracking/outputs/mytestmot17-sort.pkl']' returned non-zero exit status 1.
```

**Comment by JingweiZhang12** [comment]
The similarity metrics in the evaluation of MOT could consume much RAM. We will study the details later.

**Comment by csdingithub** [comment]
> The involved large data matrices in the evaluation of MOT which consumes much RAM is inevitable. We will study the details later.

Thanks for your reply! I suggest that for MOT task you can use the evaluation code like FairMOT![https://github.com/ifzhang/FairMOT](url) For MOT task, the output storing in only a one file is not suitable! Thanks a lot!

**Comment by JingweiZhang12** [comment]
Thanks for your suggestions! We'll think about it carefully!

**Comment by lpxgis** [comment]
We tried to reproduce this problem, but it didn't succeed. Running the test on **Ubuntu** will consume about 4GB of memory and 7GB on **windows**. If you still encounter this problem, please leave your comment here.
