### ISSUE TITLE
MOT17 dataset error when using /tools/analysis/mot/mot_error_visualize.py 

### ISSUE THREAD

**Issue by Evil1m** [open-mmlab/mmtracking#534]
English: 
When I want to use the mmtracking tool to analsis MOT17 dataset MOT task error(/tools/analysis/mot/mot_error_visualize.py )  and  this error occurred.

Command: python ./tools/analysis/mot/mot_error_visualize.py **config_file_path** **pkl_result_path** --out-dir **out_dir_path**

Error Info:
Traceback (most recent call last):
  File "/home/openmmlab/mmtracking/./tools/analysis/mot/mot_error_visualize.py", line 195, in <module>
    main()
  File "/home/openmmlab/mmtracking/./tools/analysis/mot/mot_error_visualize.py", line 105, in main
    resfiles, video_names, tmp_dir = dataset.format_results(
ValueError: too many values to unpack (expected 3

It seems that the format_results function in the dataset  returned  incorrect values length
and i go to https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/datasets/mot_challenge_dataset.py#L193  ,return 4 values 
but https://github.com/open-mmlab/mmtracking/blob/master/tools/analysis/mot/mot_error_visualize.py#L105  only got 3 of 4 

need fix!

regards

中文:
MOT17数据集在使用官方提供的mot_error_visualize.py进行错误统计输出时运行出错
在MOT数据集  https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/datasets/mot_challenge_dataset.py#L193 中format_results 方法返回了4个值
但是在 https://github.com/open-mmlab/mmtracking/blob/master/tools/analysis/mot/mot_error_visualize.py#L105 只获取了其中的3个。
需要进行修复
谢谢

**Comment by dyhBUPT** [comment]
oh, you are right. Could you please pull requests for that bug? And then we'll fix it as soon as possible.

**Comment by pixeli99** [comment]
Thank you for your feedback！
Please change your file referring to this PR: https://github.com/open-mmlab/mmtracking/pull/538
