### ISSUE TITLE
"[Errno 2] No such file or directory: 'data/MOT20/test/MOT20-04/gt/gt.txt'' when I tested Bytetrack

### ISSUE THREAD

**Issue by l412198735** [open-mmlab/mmtracking#583]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
'[Errno 2] No such file or directory: 'data/MOT17/test/MOT17-01-DPM/gt/gt.txt'' When I tested Bytetrack with "python tools/test.py configs/mot/bytetrack/bytetrack_yolox_x_crowdhuman_mot20-private.py --eval track”

‘[Errno 2] No such file or directory: 'data/MOT20/test/MOT20-04/gt/gt.txt'’ when I tested Bytetrack with “python tools/test.py configs/mot/bytetrack/bytetrack_yolox_x_crowdhuman_mot20-private.py --eval track” 

But with code  “python tools/test.py configs/mot/bytetrack/bytetrack_yolox_x_crowdhuman_mot17-private-half.py --eval track” I can test successfully

**Reproduction**

1. What command or script did you run?

python tools/test.py configs/mot/bytetrack/bytetrack_yolox_x_crowdhuman_mot20-private.py --eval track
python tools/test.py configs/mot/bytetrack/bytetrack_yolox_x_crowdhuman_mot17-private.py --eval track

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Not modified

4. What dataset did you use and what task did you run?
MOT17 and MOT20

**Error traceback**
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 4479/4479, 18.1 task/s, elapsed: 247s, ETA:     0sEvaluate CLEAR MOT results.
Traceback (most recent call last):
  File "tools/test.py", line 225, in <module>
    main()
  File "tools/test.py", line 215, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/media/haoli/DATA/My_project/MOT/mmtracking/mmtrack/datasets/mot_challenge_dataset.py", line 402, in evaluate
    gt_content = self.file_client.get(gt_file)
  File "/home/haoli/anaconda3/envs/mmtracking/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 1014, in get
    return self.client.get(filepath)
  File "/home/haoli/anaconda3/envs/mmtracking/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 535, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/MOT20/test/MOT20-04/gt/gt.txt'

**Comment by pixeli99** [comment]
Does the file `gt.txt` exist in the path `data/MOT20/test/MOT20-04/gt/`?

Have you checked？

**Comment by l412198735** [comment]
> 该文件是否`gt.txt`存在于路径中`data/MOT20/test/MOT20-04/gt/`？
> 
> 你检查过吗？

I found that ‘/gt/gt.txt’ does not exist in the test set of MOT17 and MOT20, while the train set does. I got the dataset from [MOTChallenge](https://motchallenge.net/data/MOT17/)

![image](https://user-images.githubusercontent.com/24469194/172369487-5f8859b4-0dc4-4d0f-84b6-d03c6a4cb405.png)
![image](https://user-images.githubusercontent.com/24469194/172370117-8354d78d-c782-4ee3-9666-6dd002539763.png)

**Comment by pixeli99** [comment]
Well, I see. You want to eval the **test** set, but you can't do it locally. The **MOT challenge** doesn't provide gt.txt for test set verification, so `--eval track` mat raise error.

**Comment by l412198735** [comment]
> Well, I see. You want to eval the **test** set, but you can't do it locally. The **MOT challenge** doesn't provide gt.txt for test set verification, so `--eval track` may raise error.

Thanks for your answer!!

**Comment by pixeli99** [comment]
You're welcome. Hope everything goes well with you.🙂
