### ISSUE TITLE
Got error after 2 hours of testing

### ISSUE THREAD

**Issue by HelenTsvetkova** [open-mmlab/mmtracking#589]
Is it okay..?

```
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 29528/29528, 5.0 task/s, elapsed: 5959s, ETA:     0sEvaluate CLEAR MOT results.
Traceback (most recent call last):
  File "tools/test.py", line 225, in <module>
    main()
  File "tools/test.py", line 215, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/home/helen/tracking_projects/mmtracking-master/mmtrack/datasets/mot_challenge_dataset.py", line 438, in evaluate
    'Please run'
ImportError: Please runpip install git+https://github.com/JonathonLuiten/TrackEval.gitto manually install trackeval
```

**Comment by dyhBUPT** [comment]
That occurs because you try to perfom MOT evaluation but don't have the `TrackEval` package.
Please run `
pip install git+https://github.com/JonathonLuiten/TrackEval.git` to install it.
