### ISSUE TITLE
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wjq842121846** [open-mmlab/mmtracking#603]
(open-mmlab) [root@299134adb6d7 mmtracking]# python demo/demo_mot_vis.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4
Traceback (most recent call last):
  File "demo/demo_mot_vis.py", line 9, in <module>
    from mmtrack.apis import inference_mot, init_model
  File "/mnt/mmtracking/mmtrack/apis/__init__.py", line 2, in <module>
    from .inference import inference_mot, inference_sot, inference_vid, init_model
  File "/mnt/mmtracking/mmtrack/apis/inference.py", line 9, in <module>
    from mmcv.ops import RoIPool
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/active_rotated_filter.py", line 12, in <module>
    ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

当我按照安装要求安装完成后运行demo，发生此报错，一直未能解决，希望大神帮忙解决下，感激不尽

**Comment by dyhBUPT** [comment]
Hi, it seems it is caused by the mmcv/cuda version conflict. Please make sure you have install mmcv sucessfully.
Specifically, you can run [check_installation.py](https://github.com/open-mmlab/mmcv/blob/master/.dev_scripts/check_installation.py) in mmcv to check the installation of mmcv-full.

Best wishes.

**Comment by asaini68-gtri** [comment]
> (open-mmlab) [root@299134adb6d7 mmtracking]# python demo/demo_mot_vis.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4 Traceback (most recent call last): File "demo/demo_mot_vis.py", line 9, in from mmtrack.apis import inference_mot, init_model File "/mnt/mmtracking/mmtrack/apis/**init**.py", line 2, in from .inference import inference_mot, inference_sot, inference_vid, init_model File "/mnt/mmtracking/mmtrack/apis/inference.py", line 9, in from mmcv.ops import RoIPool File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/**init**.py", line 2, in from .active_rotated_filter import active_rotated_filter File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/active_rotated_filter.py", line 12, in ['active_rotated_filter_forward', 'active_rotated_filter_backward']) File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext ext = importlib.import_module('mmcv.' + name) File "/root/miniconda3/envs/open-mmlab/lib/python3.7/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
> 
> 当我按照安装要求安装完成后运行demo，发生此报错，一直未能解决，希望大神帮忙解决下，感激不尽

Were you able to find a fix for this? I am installing the same mmcv-full aligned with my cuda version and continue to get the same issue.

**Comment by JielinYang** [comment]
> > (open-mmlab) [root@299134adb6d7 mmtracking]# python demo/demo_mot_vis.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4 Traceback (most recent call last): File "demo/demo_mot_vis.py", line 9, in from mmtrack.apis import inference_mot, init_model File "/mnt/mmtracking/mmtrack/apis/**init**.py", line 2, in from .inference import inference_mot, inference_sot, inference_vid, init_model File "/mnt/mmtracking/mmtrack/apis/inference.py", line 9, in from mmcv.ops import RoIPool File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/**init**.py", line 2, in from .active_rotated_filter import active_rotated_filter File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/active_rotated_filter.py", line 12, in ['active_rotated_filter_forward', 'active_rotated_filter_backward']) File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext ext = importlib.import_module('mmcv.' + name) File "/root/miniconda3/envs/open-mmlab/lib/python3.7/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
> > 当我按照安装要求安装完成后运行demo，发生此报错，一直未能解决，希望大神帮忙解决下，感激不尽
> 
> Were you able to find a fix for this? I am installing the same mmcv-full aligned with my cuda version and continue to get the same issue.

Have you solved this problem? I tried all possible ways but don't work

**Comment by JielinYang** [comment]
Run demo succesfully! I configure the environment following tutorials(updated several years ago).  And version information:
- Ubuntu 20.04, GPU RTX 2080Ti, Pytorch 1.10.0, CUDA 11.3, python 3.8
- mmcv-full 1.7.2, mmdet 2.28.0, mmtracking 0.14.0

There are many errors：
1. libcudart.so.10.2: cannot open shared object file: 
- download libcudart.so.10.2 at 链接: https://pan.baidu.com/s/1JctSCWNLkuO44LkmH3hqeA?pwd=cbh8 提取码: cbh8
- put it under /usr/local/cuda-11.3/targets/x86_64-linux/lib/
- configure environment variables: export LD_LIBRARY_PATH=/usr/local/cuda-11.3/targets/x86_64-linux/lib:$LD_LIBRARY_PATH
2. RuntimeError: CUDA error: no kernel image is available for execution on the device
- change GPU from 30xx to 20xx.
