### ISSUE TITLE
Q: Why Recommend MMCV build with cuda10.2?

### ISSUE THREAD

**Issue by kylelul** [open-mmlab/mmtracking#727]
I'm a newcomer trying mmtracking. 

When working along with this environment installation [steps](https://github.com/open-mmlab/mmtracking/blob/master/docs/en/install.md) . I found a error from mmcv about cuda10.2 since I am using cuda11.4. 

**Is 10.2 cuda must?**

And this occurred 2021 in your mmsegmentation [issue.](https://github.com/open-mmlab/mmsegmentation/issues/943) 

Well after I reinstall the mmcv 1.6.1 with cuda==11.3 following the instruction in your [document](https://mmcv.readthedocs.io/en/latest/get_started/installation.html). 
` pip install mmcv-full==1.6.1 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html`

The error above solved but another error occurred. So ANY IDEAS? 

`(open-mmlab) kira@kiracca-vm:~/projects/lzk/DeepLearning/CV/other_repos/mmtracking$ python demo/demo_mot_vis.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4
Traceback (most recent call last):
  File "demo/demo_mot_vis.py", line 9, in <module>
    from mmtrack.apis import inference_mot, init_model
  File "/home/kira/projects/lzk/DeepLearning/CV/other_repos/mmtracking/mmtracking/mmtrack/apis/__init__.py", line 2, in <module>
    from .inference import inference_mot, inference_sot, inference_vid, init_model
  File "/home/kira/projects/lzk/DeepLearning/CV/other_repos/mmtracking/mmtracking/mmtrack/apis/inference.py", line 9, in <module>
    from mmcv.ops import RoIPool
  File "/home/kira/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/kira/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/active_rotated_filter.py", line 12, in <module>
    ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
  File "/home/kira/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/kira/miniconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/kira/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE`

**Comment by dyhBUPT** [comment]
Hi, you can use other versions of cuda/mmcv according to https://mmcv.readthedocs.io/en/latest/get_started/installation.html
