### ISSUE TITLE
When I want to run demo.py with strongsort, I get the following error:

### ISSUE THREAD

**Issue by lzzppp** [open-mmlab/mmtracking#748]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When I want to run demo.py with strongsort, I get an error that the input data is missing something.

**Reproduction**

1. What command or script did you run?
python -W ignore demo/demo_mot_vis.py configs/mot/strongsort/strongsort_yolox_x_8xb4-80e_crowdhuman-mot20train_test-mot20test.py --input demo/demo.mp4 --output mot.mp4

```none
A placeholder for the command.
```

3. Did you make any modifications on the code or config? Did you understand what you have modified?
NO, i dont mofify anything

4. What dataset did you use and what task did you run?

demo.mp4

**Environment**

1. Please run `python mmtrack/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
Traceback (most recent call last):
  File "/home/lzp/mmtracking/demo/demo_mot_vis.py", line 119, in <module>
    main(args)
  File "/home/lzp/mmtracking/demo/demo_mot_vis.py", line 88, in main
    result = inference_mot(model, img, frame_id=i)
  File "/home/lzp/mmtracking/mmtrack/apis/inference.py", line 128, in inference_mot
    result = model.test_step(data)[0]
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 301, in _run_forward
    results = self(**data, mode=mode)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lzp/mmtracking/mmtrack/models/mot/base.py", line 108, in forward
    return self.predict(inputs, data_samples, **kwargs)
  File "/home/lzp/mmtracking/mmtrack/models/mot/deep_sort.py", line 99, in predict
    det_results = self.detector.predict(img, data_samples)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmdet/models/detectors/single_stage.py", line 110, in predict
    results_list = self.bbox_head.predict(
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 197, in predict
    predictions = self.predict_by_feat(
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmdet/models/dense_heads/yolox_head.py", line 317, in predict_by_feat
    self._bbox_post_process(
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmdet/models/dense_heads/yolox_head.py", line 387, in _bbox_post_process
    assert img_meta.get('scale_factor') is not None
AssertionError

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by pixeli99** [comment]
Hi,

The reason for the error is that the `scale_factor` is not found in the meta information of the image, which stores the scale of the image.

What is your mmdet version?
You can use `mmdet.__ version__ ` to show.

**Comment by lzzppp** [comment]
> 你好，
> 
> 报错的原因是`scale_factor`图片的元信息中没有找到，存储了图片的比例尺。
> 
> 你的 mmdet 版本是多少？ 你可以`mmdet.__ version__ `用来展示。

Hi, my version is '3.0.0rc2'

**Comment by pixeli99** [comment]
In my opinion, there should be no such error, can you make a breakpoint here to see what `keys` are in `img_meta`?

**Comment by shen-ttt** [comment]
Ran into the same error for ByteTrack and StrongSort in the dev-1.x branch, while deepsort works OK. 

Comparing the config files, val_dataloader is different in deepsort compared to the other two trackers. Deepsort inherit the val_dataloader from ../../_base_/datasets/mot_challenge.py, while ByteTrack and StrongSort overwrite val_dataloader with its own. Delete their own val_dataloader and everything works fine. 

Here is the dev environment I am using: 
```
mmcls                 1.0.0rc5           
mmcv                  2.0.0rc3           
mmdet                 3.0.0rc5          
mmengine              0.4.0              
mmtrack               1.0.0rc1
```
Here is the error message: 

```
Traceback (most recent call last):
  File "demo/demo_mot_vis.py", line 119, in <module>
    main(args)
  File "demo/demo_mot_vis.py", line 88, in main
    result = inference_mot(model, img, frame_id=i)
  File "/home/tong/code/mmtracking-tomp/mmtrack/apis/inference.py", line 131, in inference_mot
    result = model.test_step(data)[0]
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py", line 314, in _run_forward
    results = self(**data, mode=mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tong/code/mmtracking-tomp/mmtrack/models/mot/base.py", line 108, in forward
    return self.predict(inputs, data_samples, **kwargs)
  File "/home/tong/code/mmtracking-tomp/mmtrack/models/mot/byte_track.py", line 104, in predict
    det_results = self.detector.predict(img, data_samples)
  File "/home/tong/code/mmdetection/mmdet/models/detectors/single_stage.py", line 110, in predict
    results_list = self.bbox_head.predict(
  File "/home/tong/code/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 197, in predict
    predictions = self.predict_by_feat(
  File "/home/tong/code/mmdetection/mmdet/models/dense_heads/yolox_head.py", line 317, in predict_by_feat
    self._bbox_post_process(
  File "/home/tong/code/mmdetection/mmdet/models/dense_heads/yolox_head.py", line 387, in _bbox_post_process
    assert img_meta.get('scale_factor') is not None
AssertionError
```

**Comment by anilkunchalaece** [comment]
I tried @shen-ttt suggestion and it seems to be working for me as well.
Comment the following 
```
val_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='VideoSampler'),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotations/half-val_cocoformat.json',
        data_prefix=dict(img_path='train'),
        ref_img_sampler=None,
        load_as_video=True,
        test_mode=True,
        pipeline=test_pipeline))

```
And add the following
```
val_dataloader = dict(
    dataset=dict(ann_file='annotations/train_cocoformat.json'))
```
