### ISSUE TITLE
Training using qdtrack on custom COCOvideo Datasets fails.

### ISSUE THREAD

**Issue by YOOHYOJEONG** [open-mmlab/mmtracking#755]
Hi, 
I'm trying to use QDTrack of MMTrack on a custom dataset organized as COCOVideo Dataset as shown in the documentation. But when running the tools/test.py script I get an error because the "results" variable in "mmtracking/mmtrack/datasets/pipelines/formatting.py", line 394" is a string instead of a dict -> loading the dataset somehow fails.
I have searched related issues but cannot get the expected help.

Error traceback:
```shell
Traceback (most recent call last):
  File "tools/train.py", line 210, in <module>
    main()
  File "tools/train.py", line 82, in main
    cfg = Config.fromfile(args.config)
  File "/workspace/mmcv/mmcv/utils/config.py", line 341, in fromfile
    use_predefined_variables)
  File "/workspace/mmcv/mmcv/utils/config.py", line 208, in _file2dict
    mod = import_module(temp_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp29ab6hai/tmpstszw6w4.py", line 41, in <module>
  File "/workspace/mmdetection/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/workspace/mmcv/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/workspace/mmcv/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/workspace/hjyoo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/workspace/hjyoo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/workspace/hjyoo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/workspace/hjyoo/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/workspace/hjyoo/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/workspace/hjyoo/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/hjyoo/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/mmdetection/mmdet/datasets/custom.py", line 218, in __getitem__
    data = self.prepare_train_img(idx)
  File "/workspace/mmtracking/mmtrack/datasets/coco_video_dataset.py", line 303, in prepare_train_img
    return self.prepare_data(idx)
  File "/workspace/mmtracking/mmtrack/datasets/coco_video_dataset.py", line 291, in prepare_data
    return self.pipeline(results)
  File "/workspace/mmdetection/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/workspace/mmtracking/mmtrack/datasets/pipelines/formatting.py", line 547, in __call__
    _results = super().__call__(_results)
  File "/workspace/mmtracking/mmtrack/datasets/pipelines/formatting.py", line 358, in __call__
    _results = self._add_default_meta_keys(_results)
  File "/workspace/mmtracking/mmtrack/datasets/pipelines/formatting.py", line 394, in _add_default_meta_keys
    img = results['img']
TypeError: string indices must be integers

Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7ff258428f80>
Traceback (most recent call last):
  File "/usr/lib/python3.7/tempfile.py", line 587, in __del__
    self.close()
  File "/usr/lib/python3.7/tempfile.py", line 583, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp29ab6hai/tmpstszw6w4.py'
```

Dataset annotations json file (only a shortened version):
``` json
{
"categories": [{"id": 1, "name": "cattle"}], 
"videos": [{"id": 1, "name": "gangun_dairy-cattle_walking_12"}, {"id": 2, "name": "gangun_dairy-cattle_walking_21_1"}],
"images": [
{"id": 1, "video_id": 1, "frame_id": 0, "file_name": "gangun_dairy-cattle_walking_12/gangun_dairy-cattle_ch01_weaning_211104_1009_0001.png", "height": 1500, "width": 2880}, 
{"id": 2, "video_id": 1, "frame_id": 1, "file_name": "gangun_dairy-cattle_walking_12/gangun_dairy-cattle_ch01_weaning_211104_1009_0002.png", "height": 1500, "width": 2880}],
"annotations": [
{"id": 1, "image_id": 1, "video_id": 1, "category_id": 1, "instance_id": 1, "occluded": 0, "truncated": 0, "iscrowd": 0, "ignore": 0, "is_vid_train_frame": 0, "visibility": 1.0, "bbox": [1337, 155, 187, 135], "area": 25245},
{"id": 2, "image_id": 2, "video_id": 1, "category_id": 1, "instance_id": 1, "occluded": 0, "truncated": 0, "iscrowd": 0, "ignore": 0, "is_vid_train_frame": 0, "visibility": 1.0, "bbox": [1337, 155, 187, 135], "area": 25245}]
}
```

I tried to use Tracktor with QDTrack and a Faster R-CNN detector which I trained previously using MMDet. Config:
``` python
model = dict(
    type='QDTrack',
    detector=dict(
        type='FasterRCNN',
        backbone=dict(
            type='ResNet',
            depth=50,
            num_stages=4,
            out_indices=(0, 1, 2, 3),
            frozen_stages=1,
            norm_cfg=dict(type='BN', requires_grad=True),
            norm_eval=True,
            style='pytorch'),
        neck=dict(
            type='FPN',
            in_channels=[256, 512, 1024, 2048],
            out_channels=256,
            num_outs=5),
        rpn_head=dict(
            type='RPNHead',
            in_channels=256,
            feat_channels=256,
            anchor_generator=dict(
                type='AnchorGenerator',
                scales=[8],
                ratios=[0.5, 1.0, 2.0],
                strides=[4, 8, 16, 32, 64]),
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[.0, .0, .0, .0],
                target_stds=[1.0, 1.0, 1.0, 1.0]),
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
            loss_bbox=dict(
                type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
        roi_head=dict(
            type='StandardRoIHead',
            bbox_roi_extractor=dict(
                type='SingleRoIExtractor',
                roi_layer=dict(
                    type='RoIAlign', output_size=7, sampling_ratio=0),
                out_channels=256,
                featmap_strides=[4, 8, 16, 32]),
            bbox_head=dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=1,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.1, 0.1, 0.2, 0.2]),
                reg_class_agnostic=False,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', loss_weight=1.0))),
        train_cfg=dict(
            embed=dict(assigner=dict(neg_iou_thr=0.5)),
            rpn=dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.7,
                    neg_iou_thr=0.3,
                    min_pos_iou=0.3,
                    match_low_quality=True,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=256,
                    pos_fraction=0.5,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=False),
                allowed_border=-1,
                pos_weight=-1,
                debug=False),
            rpn_proposal=dict(
                nms_pre=2000,
                max_per_img=1000,
                nms=dict(type='nms', iou_threshold=0.7),
                min_bbox_size=0),
            rcnn=dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.5,
                    neg_iou_thr=0.5,
                    min_pos_iou=0.5,
                    match_low_quality=False,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                pos_weight=-1,
                debug=False)),
        test_cfg=dict(
            rpn=dict(
                nms_pre=1000,
                max_per_img=1000,
                nms=dict(type='nms', iou_threshold=0.7),
                min_bbox_size=0),
            rcnn=dict(
                score_thr=0.05,
                nms=dict(type='nms', iou_threshold=0.5),
                max_per_img=100)),
        init_cfg=dict(
                type='Pretrained', checkpoint='/workspace/mmtracking/cattle_tracking/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'))
        # soft-nms is also supported for rcnn testing
        # e.g., nms=dict(type='soft_nms', iou_threshold=0.5, min_score=0.05)
    ),
    track_head=dict(
        type='QuasiDenseTrackHead',
        track_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        track_head=dict(
            type='QuasiDenseEmbedHead',
            num_convs=4,
            num_fcs=1,
            embed_channels=256,
            norm_cfg=dict(type='GN', num_groups=32),
            loss_track=dict(type='MultiPosCrossEntropyLoss', loss_weight=0.25),
            loss_track_aux=dict(
                type='L2Loss',
                neg_pos_ub=3,
                pos_margin=0,
                neg_margin=0.1,
                hard_mining=True,
                loss_weight=1.0)),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0),
        train_cfg=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.5,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='CombinedSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=3,
                add_gt_as_proposals=True,
                pos_sampler=dict(type='InstanceBalancedPosSampler'),
                neg_sampler=dict(type='RandomSampler'))),
        init_cfg = dict(
            type = 'Pretrained',
            checkpoint = '/dataset-14T/hj_cattle/pretrained/qdtrack-frcnn_r50_fpn_12e_bdd100k-13328aed.pth'),
    tracker=dict(
        type='QuasiDenseTracker',
        init_score_thr=0.9,
        obj_score_thr=0.5,
        match_score_thr=0.5,
        memo_tracklet_frames=30,
        memo_backdrop_frames=1,
        memo_momentum=0.8,
        nms_conf_thr=0.5,
        nms_backdrop_iou_thr=0.3,
        nms_class_iou_thr=0.7,
        with_cats=True,
        match_metric='bisoftmax'))
# dataset settings
dataset_type = 'CocoVideoDataset'
data_root = '/dataset-14T/hj_cattle/'
img_norm_cfg = dict(
    mean=[103.530, 116.280, 123.675], std=[1.0, 1.0, 1.0], to_rgb=False)
train_pipeline = [
    dict(type='LoadMultiImagesFromFile', to_float32=True),
    dict(type='SeqLoadAnnotations', with_bbox=True, with_ins_id=True),
    dict(
        type='SeqResize',
        img_scale=(1088, 1088),
        share_params=True,
        ratio_range=(0.8, 1.2),
        keep_ratio=True,
        bbox_clip_border=False),
    dict(type='SeqPhotoMetricDistortion', share_params=True),
    dict(
        type='SeqRandomCrop',
        share_params=False,
        crop_size=(1088, 1088),
        bbox_clip_border=False),
    dict(type='SeqRandomFlip', share_params=True, flip_ratio=0.5),
    dict(type='SeqNormalize', **img_norm_cfg),
    dict(type='SeqPad', size_divisor=32),
    dict(type='SeqDefaultFormatBundle'),
    dict(
        type='SeqCollect',
        keys=['img', 'gt_bboxes', 'gt_labels', 'gt_match_indices'],
        ref_prefix='ref'),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1088, 1088),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='VideoCollect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=8,
    train=dict(
        type=dataset_type,
        classes=['cattle'],
        # visibility_thr=-1,
        # track_visibility_thr=-1,
        ann_file='/dataset-14T/hj_cattle/track/dairy_cattle_walking_tracking_train.json',
        img_prefix=data_root + 'train/',
        # ref_img_sampler=dict(num_ref_imgs=1, scope=10, method='uniform'),
        ref_img_sampler=dict(num_ref_imgs=1, frame_range=10, filter_key_img=True, method='uniform'),
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file='/dataset-14T/hj_cattle/track/dairy_cattle_walking_tracking_val.json',
        classes=['cattle'],
        img_prefix=data_root + 'val/',
        ref_img_sampler=None,
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file='/dataset-14T/hj_cattle/track/dairy_cattle_walking_tracking_val.json',
        img_prefix=data_root + 'val/',
        classes=['cattle'],
        ref_img_sampler=None,
        pipeline=test_pipeline))

# optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
# optimizer_config = dict(_delete_=True, grad_clip=dict(max_norm=35, norm_type=2))
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(policy='step', step=[3])
# checkpoint saving
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=100,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# runtime settings
dist_params = dict(backend='nccl')
log_level = 'INFO'
workflow = [('train', 1)]
evaluation = dict(metric=['bbox', 'track'], interval=1)
resume_from = None
load_from = None
work_dir = 'exps/tracker/Cattle_tracking/'
seed = 0
set_random_seed(0, deterministic=False)
device = 'cuda'
gpu_ids = range(1,2)
total_epochs = 30

# disable opencv multithreading to avoid system being overloaded
opencv_num_threads = 0
# set multi-process start method as `fork` to speed up the training
mp_start_method = 'fork'
```

Environment (I also tested using the most recent commit on the main branch of mmtrack - same problem):
``` shell
TorchVision: 0.8.2
OpenCV: 4.5.3
MMCV: 1.3.8
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.1
MMTracking: 0.7.0+
```

Is there maybe an error in my config/dataset yaml? Or could there be a bug in the code?
Any help is much appreciated, thank you!

**Comment by pixeli99** [comment]
Hi,

It seems that it is a problem with the dataset format. You can test it yourself first(`the link below`), and I'll take a closer look at your issue content later.😀
https://github.com/open-mmlab/mmtracking/blob/87d55eccf41e6a38c6d28c64bc094430764bea82/tests/test_data/test_datasets/test_mot_challenge_dataset.py#L1
