### ISSUE TITLE
ImportError: DLL load failed while importing _ext

### ISSUE THREAD

**Issue by senovr** [open-mmlab/mmtracking#765]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**
After successful build of mmtracking, it fails when running mot test script.

**Reproduction**

1. What command or script did you run?

```
python demo/demo_mot_vis.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4
```

**Environment**

1. Please run `python mmtrack/utils/collect_env.py` 
Can not do it, fails with the same traceback.

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch  - pip
   - pip venv, python 3.10
   - 

**Error traceback**
If applicable, paste the error trackback here.

```
Traceback (most recent call last):
  File "C:\Users\user\repos\mmtracking\demo\demo_mot_vis.py", line 9, in <module>
    from mmtrack.apis import inference_mot, init_model
  File "c:\users\user\repos\mmtracking\mmtrack\apis\__init__.py", line 2, in <module>
    from .inference import inference_mot, inference_sot, inference_vid, init_model
  File "c:\users\user\repos\mmtracking\mmtrack\apis\inference.py", line 9, in <module>
    from mmcv.ops import RoIPool
  File "C:\Users\user\repos\mmtracking\.venv-mmlab\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\Users\user\repos\mmtracking\.venv-mmlab\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\Users\user\repos\mmtracking\.venv-mmlab\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.
```

**Comment by pixeli99** [comment]
Hi,
senovr,

Maybe you should install `mmcv-full` instead of `mmcv`.

**Comment by senovr** [comment]
@pixeli99 .
Here is my workflow for installation:
1. cloning mmtracking repo and cd into it:
```
git clone https://github.com/open-mmlab/mmtracking.git
cd mmtracking
```
2. Creating new .venv with pip and activating it (via git bash on Windows):
```
python -m venv .venv
source .venv/Scripts/activate
```
3. Installing vot-challenge toolkit
`pip install git+https://github.com/votchallenge/toolkit.git`
4. Installing torch ( currently, 1.13+ cu11.6 is available from torch website)
`pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116`

5. installing mmcv-full
`pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.12/index.html`

6. Installing mmdet
`pip install mmdet`

7. Install build requirements and then install MMTracking.
```
pip install -r requirements/build.txt
pip install -v -e .
```

8. run test script
`python demo/demo_mot_vis.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4`

Traceback with an error above.
