### ISSUE TITLE
ValueError: need at least one array to concatenate.when train selsa on my own datasets(only one class).

### ISSUE THREAD

**Issue by Bigfishering** [open-mmlab/mmtracking#773]
datasets have been converted to cocovid,and i also have changed the config file,claasses and the num_class,but still met this issue.
what can i do?

Traceback (most recent call last):
  File "tools/train.py", line 213, in <module>
    main()
  File "tools/train.py", line 209, in main
    meta=meta)
  File "/home/ecust/txx/docker/container/mega/fgfa_pytorch/mega.pytorch/mmtracking-master/mmtrack/apis/train.py", line 175, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ecust/software/anaconda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ecust/software/anaconda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/ecust/software/anaconda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/ecust/software/anaconda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/ecust/software/anaconda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 944, in __init__
    self._reset(loader, first_iter=True)
  File "/home/ecust/software/anaconda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 975, in _reset
    self._try_put_index()
  File "/home/ecust/software/anaconda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
  File "/home/ecust/software/anaconda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/ecust/software/anaconda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 229, in __iter__
    for idx in self.sampler:
  File "/home/ecust/software/anaconda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by dyhBUPT** [comment]
Hi, it seems there is some error when loading data. Please check your dataset.

**Comment by Bigfishering** [comment]
@dyhBUPT thanks，i have fixed that out!

**Comment by IncludeMathH** [comment]
> @dyhBUPT thanks，i have fixed that out!

Now I have the same problem. How do you solve it?

**Comment by BiBiKo219** [comment]
@Bigfishering @IncludeMathH I have also encountered this issue. May I ask how you have resolved it?
