### ISSUE TITLE
Incompatibility issue between mmtrack, numpy and scipy.

### ISSUE THREAD

**Issue by AnabelGRios** [open-mmlab/mmtracking#820]
Hello. First of all, thank you for your wonderful work. I am trying to use mmtrack to do multi-object tracking. Though the installation works, I cannot load the mmtrack.apis module because of a incompatibility between the needed versions of numpy and scipy. I have searched related issues, but I have not found anything. I installed mmtrack version 0.14.0 by clonning the github repo.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Fail to complete the following import:
`from mmtrack import apis`

The problem seems to be that something is trying to import a numpy array compiled with version >=1.23 when the numpy version required for mmtrack is 1.22.4, causing this to fail. I tried to update numpy to version 1.23, but this version does not have compatibility with the required version for scipy (1.7.3), so I tried also updating scipy to 1.8, but scipy version >= 1.7.3 do not have compatibility with mmtrack.

**Reproduction**

OS: Windows
I followed the instructions in [https://github.com/open-mmlab/mmtracking/blob/master/docs/en/install.md](https://github.com/open-mmlab/mmtracking/blob/master/docs/en/install.md). 

I already had a python venv environment with Python 3.9, PyTorch 1.13.1 and cuda 11.6. In that environment, I installed mmcv-full version 1.7.0 using
`pip install mmcv-full==1.7.0 -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.13/index.html`
as said in [https://mmcv.readthedocs.io/en/latest/get_started/installation.html](https://mmcv.readthedocs.io/en/latest/get_started/installation.html)
and mmdet version 2.27.0, both of them compatible with mmtrack version 0.14.0.
Then I installed mmtrack using:
```
git clone https://github.com/open-mmlab/mmtracking.git
cd mmtracking
pip install -r requirements/build.txt
pip install -v -e .  # or "python setup.py develop"
```
and the MOT extra dependency:
`pip install git+https://github.com/JonathonLuiten/TrackEval.git`
Then, the verification step
`python demo/demo_mot_vis.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4`
did not run and I encountered the numpy error.

**Environment**

Output of `python mmtrack/utils/collect_env.py`:
```
UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
sys.platform: win32
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1650 with Max-Q Design
CUDA_HOME: None
MSVC: Compilador de optimización de C/C++ de Microsoft (R) versión 19.34.31937 para x64
GCC: n/a
PyTorch: 1.13.1+cu116
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.14.1+cu116
OpenCV: 4.7.0
MMCV: 1.7.0
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 11.6
MMTracking: 0.14.0+b1679f9
```

**Error traceback**
The error traceback is the following:
```
Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\agr\LibreriasPytorch\mmtracking\mmtrack\apis\__init__.py", line 2, in <module>
    from .inference import inference_mot, inference_sot, inference_vid, init_model
  File "C:\Users\agr\LibreriasPytorch\mmtracking\mmtrack\apis\inference.py", line 12, in <module>
    from mmdet.datasets.pipelines import Compose
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\datasets\__init__.py", line 2, in <module>
    from .builder import DATASETS, PIPELINES, build_dataloader, build_dataset
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\datasets\builder.py", line 15, in <module>
    from .samplers import (ClassAwareSampler, DistributedGroupSampler,
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\datasets\samplers\__init__.py", line 2, in <module>
    from .class_aware_sampler import ClassAwareSampler
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\datasets\samplers\class_aware_sampler.py", line 8, in <module>
    from mmdet.core.utils import sync_random_seed
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\__init__.py", line 6, in <module>
    from .hook import *  # noqa: F401, F403
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\hook\__init__.py", line 6, in <module>
    from .sync_norm_hook import SyncNormHook
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\hook\sync_norm_hook.py", line 8, in <module>
    from ..utils.dist_utils import all_reduce_dict
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\utils\__init__.py", line 4, in <module>
    from .misc import (center_of_mass, filter_scores_and_topk, flip_tensor,
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\utils\misc.py", line 8, in <module>
    from ..mask.structures import BitmapMasks, PolygonMasks
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\mask\__init__.py", line 3, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\mask\structures.py", line 7, in <module>
    import pycocotools.mask as maskUtils
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools\_mask.pyx", line 23, in init pycocotools._mask
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```

**Comment by pixeli99** [comment]
Hi,
The problem about numpy does exist. We will update this dependency as soon as possible. You can try to install version 1.21 directly, such as:
`pip install numpy==1.21.0`,
If the error is still reported, you can refer to the following version to try.
![image](https://user-images.githubusercontent.com/46072190/212473177-eafeec8f-b901-476b-a2b2-a882401d0b4d.png)
If you still have questions, feel free to leave a message.

**Comment by AnabelGRios** [comment]
Hi, thanks for your quick response. I tried installing numpy version 1.21.0, but I got another error:
```
C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\agr\LibreriasPytorch\mmtracking\demo\demo_mot_vis.py", line 9, in <module>
    from mmtrack.apis import inference_mot, init_model
  File "c:\users\agr\libreriaspytorch\mmtracking\mmtrack\apis\__init__.py", line 2, in <module>
    from .inference import inference_mot, inference_sot, inference_vid, init_model
  File "c:\users\agr\libreriaspytorch\mmtracking\mmtrack\apis\inference.py", line 12, in <module>
    from mmdet.datasets.pipelines import Compose
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\datasets\__init__.py", line 2, in <module>
    from .builder import DATASETS, PIPELINES, build_dataloader, build_dataset
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\datasets\builder.py", line 15, in <module>
    from .samplers import (ClassAwareSampler, DistributedGroupSampler,
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\datasets\samplers\__init__.py", line 2, in <module>
    from .class_aware_sampler import ClassAwareSampler
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\datasets\samplers\class_aware_sampler.py", line 8, in <module>
    from mmdet.core.utils import sync_random_seed
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\__init__.py", line 6, in <module>
    from .hook import *  # noqa: F401, F403
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\hook\__init__.py", line 6, in <module>
    from .sync_norm_hook import SyncNormHook
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\hook\sync_norm_hook.py", line 8, in <module>
    from ..utils.dist_utils import all_reduce_dict
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\utils\__init__.py", line 4, in <module>
    from .misc import (center_of_mass, filter_scores_and_topk, flip_tensor,
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\utils\misc.py", line 8, in <module>
    from ..mask.structures import BitmapMasks, PolygonMasks
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\mask\__init__.py", line 3, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\mmdet\core\mask\structures.py", line 7, in <module>
    import pycocotools.mask as maskUtils
  File "C:\Users\agr\Environments\PyT1.13\lib\site-packages\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools\_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
So I tried with numpy version 1.23.5 and scipy 1.7.3. Though the import works, I still get a warning about the incompatibility between scipy 1.7.3 and numpy >= 1.23.0.

**Comment by pixeli99** [comment]
Hi,

This is true, but it should not affect the use :)

If you are new to `mmtrack`, you may try the latest version of mmtrack directly, and I believe you will have a better experience.
https://github.com/open-mmlab/mmtracking/tree/1.x

**Comment by AnabelGRios** [comment]
Hi,
Thank you! I was not aware of the new 1.x version of mmtrack, I have updated it!
