### ISSUE TITLE
KeyError: 'ChannelMapper is not in the neck registry'

### ISSUE THREAD

**Issue by yangxiaoyany** [open-mmlab/mmtracking#84]
hello,mmtracking is a good job .but when I train siamese rpn++,I  encountered the key error.can you help to solve it,thank you very much.

Traceback (most recent call last):
  File "tools/train.py", line 168, in <module>
    main()
  File "tools/train.py", line 141, in main
    model = build_model(cfg.model)
  File "/media/yxy/4TB/ayxy/mmtracking/mmtrack/models/builder.py", line 69, in build_model
    return build(cfg, MODELS)
  File "/media/yxy/4TB/ayxy/mmtracking/mmtrack/models/builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/yxy/anaconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/media/yxy/4TB/ayxy/mmtracking/mmtrack/models/sot/siamrpn.py", line 31, in __init__
    self.neck = build_neck(neck)
  File "/media/yxy/4TB/ayxy/mmdetection/mmdet/models/builder.py", line 42, in build_neck
    return build(cfg, NECKS)
  File "/media/yxy/4TB/ayxy/mmdetection/mmdet/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/yxy/anaconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 164, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
**KeyError: 'ChannelMapper is not in the neck registry'**

**Comment by yangxiaoyany** [comment]
I  found it is caused by mmdet version.old version do not have channel_mapper.py in mmdetection/mmdet/models/necks.
