### ISSUE TITLE
Docker Setup

### ISSUE THREAD

**Issue by Jayravalcode** [open-mmlab/mmtracking#844]
When i tried to run inference in docker i found this error, please provide solution for this issue.

Traceback (most recent call last):
  File "/mmtracking/./demo/demo_mot_vis.py", line 119, in <module>
    main(args)
  File "/mmtracking/./demo/demo_mot_vis.py", line 88, in main
    result = inference_mot(model, img, frame_id=i)
  File "/mmtracking/mmtrack/apis/inference.py", line 128, in inference_mot
    result = model.test_step(data)[0]
  File "/opt/conda/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 326, in _run_forward
    results = self(**data, mode=mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mmtracking/mmtrack/models/mot/base.py", line 108, in forward
    return self.predict(inputs, data_samples, **kwargs)
  File "/mmtracking/mmtrack/models/mot/deep_sort.py", line 99, in predict
    det_results = self.detector.predict(img, data_samples)
  File "/opt/conda/lib/python3.10/site-packages/mmdet/models/detectors/two_stage.py", line 228, in predict
    rpn_results_list = self.rpn_head.predict(
  File "/opt/conda/lib/python3.10/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 197, in predict
    predictions = self.predict_by_feat(
  File "/opt/conda/lib/python3.10/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 279, in predict_by_feat
    results = self._predict_by_feat_single(
  File "/opt/conda/lib/python3.10/site-packages/mmdet/models/dense_heads/rpn_head.py", line 233, in _predict_by_feat_single
    return self._bbox_post_process(
  File "/opt/conda/lib/python3.10/site-packages/mmdet/models/dense_heads/rpn_head.py", line 284, in _bbox_post_process
    det_bboxes, keep_idxs = batched_nms(bboxes, results.scores,
  File "/opt/conda/lib/python3.10/site-packages/mmcv/ops/nms.py", line 302, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/utils/misc.py", line 354, in new_func
    output = old_func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mmcv/ops/nms.py", line 127, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset, score_threshold,
  File "/opt/conda/lib/python3.10/site-packages/mmcv/ops/nms.py", line 27, in forward
    inds = ext_module.nms(
RuntimeError: nms_impl: implementation for device cuda:0 not found.

**Comment by aswinjose89** [comment]
Make sure you have GPU in your machine. If yes, then pass the gpu parameter via docker command. For ex:` docker run --rm -it --gpus all <image_name>`

**Comment by aswinjose89** [comment]
@Jayravalcode 
Make sure you have GPU in your machine. If yes, then pass the gpu parameter via docker command. For ex:` docker run --rm -it --gpus all <image_name>`
