### ISSUE TITLE
Facing version compatibility issue

### ISSUE THREAD

**Issue by aswinjose89** [open-mmlab/mmtracking#845]
/opt/conda/lib/python3.7/site-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
Traceback (most recent call last):
  File "demo/demo_mot_vis.py", line 9, in <module>
    from mmtrack.apis import inference_mot, init_model
  File "/mmtracking/mmtrack/apis/__init__.py", line 2, in <module>
    from .inference import inference_mot, inference_sot, inference_vid, init_model
  File "/mmtracking/mmtrack/apis/inference.py", line 9, in <module>
    from mmcv.ops import RoIPool
  File "/opt/conda/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/opt/conda/lib/python3.7/site-packages/mmcv/ops/active_rotated_filter.py", line 12, in <module>
    ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

My Cuda Version is 11.3
GPU: NVIDIA A100
GPU Driver Version: 525.85.12

Torch Version:
![image](https://user-images.githubusercontent.com/6614386/220589183-c6f6fb51-3eaa-4271-94a3-a78916ab406e.png)

**Comment by asaini68-gtri** [comment]
Same issue here. Were you able to find a solution?
