### ISSUE TITLE
[BUG]  cannot import name 'Transformer' from 'mmdet.models.layers'

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmtracking#846]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version(dev-1.x).

**Describe the bug**
```
---------------------------- Captured stderr call -----------------------------
  Traceback (most recent call last):
    File "/opt/mmtracking/demo/demo_mot_vis.py", line 119, in <module>
      main(args)
    File "/opt/mmtracking/demo/demo_mot_vis.py", line 73, in main
      register_all_modules(init_default_scope=True)
    File "/opt/mmtracking/mmtrack/utils/setup_env.py", line 25, in register_all_modules
      import mmtrack.models  # noqa: F401,F403
    File "/opt/mmtracking/mmtrack/models/__init__.py", line 14, in <module>
     from .track_heads import *  # noqa: F401,F403
   File "/opt/mmtracking/mmtrack/models/track_heads/__init__.py", line 10, in <module>
      from .stark_head import CornerPredictorHead, StarkHead
    File "/opt/mmtracking/mmtrack/models/track_heads/stark_head.py", line 9, in <module>
      from mmdet.models.layers import Transformer
  ImportError: cannot import name 'Transformer' from 'mmdet.models.layers' (/opt/conda/lib/python3.7/site-packages/mmdet/models/layers/__init__.py)
```

**Reproduction**

1. What command or script did you run?

```none
python /opt/mmtracking/demo/demo_mot_vis.py /opt/mmtracking/configs/mot/deepsort/deepsort_faster-rcnn_r50_fpn_8xb2-4e_mot17halftrain_test-mot17halfval.py --checkpoint test_integration/test_demo/ckpt/faster-rcnn_r50_fpn_4e_mot17-ffa52ae7.pth --input /opt/mmtracking/demo/demo.mp4 --output /opt/mmtracking/demo/mot_output.mp4
```

**Environment**
mmcls                  1.0.0rc5
mmcv                   2.0.0rc4  /opt/mmcv
mmdet                  3.0.0rc5
mmengine               0.5.0     /opt/mmtracking/mmengine
mmtrack                1.0.0rc1  /opt/mmtracking

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Comment by ding19980201** [comment]
Transformer in mmdet has been changed .please fix it.
sha:: 4d30934f506db189753c2f9461de3dfe5775be0b
developers has changed some codes in mmdet.models.layers.init
@pekopoke @ceykmc @hellock @vidsgr @lindahua

**Comment by JimVincentW** [comment]
I have been struggling with this all day. Some help would be really nice.

**Comment by YXlukarov** [comment]
I encountered the same bug, in mmtracking/mmtrack/models/track_heads/stark_head.py line9
`from mmdet.models.layers import Transformer`
I did not find Transformer in mmdet.models.layers, espeacially in __init__.py:
```
from .transformer import (MLP, AdaptivePadding, CdnQueryGenerator,
                          ConditionalAttention,
                          ConditionalDetrTransformerDecoder,
                          ConditionalDetrTransformerDecoderLayer,
                          DABDetrTransformerDecoder,
                          DABDetrTransformerDecoderLayer,
                          DABDetrTransformerEncoder,
                          DeformableDetrTransformerDecoder,
                          DeformableDetrTransformerDecoderLayer,
                          DeformableDetrTransformerEncoder,
                          DeformableDetrTransformerEncoderLayer,
                          DetrTransformerDecoder, DetrTransformerDecoderLayer,
                          DetrTransformerEncoder, DetrTransformerEncoderLayer,
                          DinoTransformerDecoder, DynamicConv,
                          Mask2FormerTransformerDecoder,
                          Mask2FormerTransformerDecoderLayer,
                          Mask2FormerTransformerEncoder, PatchEmbed,
                          PatchMerging, coordinate_to_encoding,
                          inverse_sigmoid, nchw_to_nlc, nlc_to_nchw)
```
while in 0.x, in mmtracking/mmtrack/models/track_heads/stark_head.py line11-12
```
from mmdet.models.utils import Transformer, build_transformer
from mmdet.models.utils.builder import TRANSFORMER
```
this uses mmdet 2.x to build functionality, mmdet/models/utils/transformer.py line538-621 is the implementation of the DETR transformer while no implementation in the same place in mmdet 3.x layers
