### ISSUE TITLE
when I run demo/

### ISSUE THREAD

**Issue by btdan** [open-mmlab/mmtracking#85]
when I use  demo/demo.mp4 as input , the demo/demo_mot.py is well done and get the ideal result .But when I use a new mp4 video as input, this program goes error. And display as follow:
python demo/demo_mot.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py  --input demo/0dbdc35ab8fc73539b569ce5d8338cfd.mp4 --output afn.mp4
2021-01-08 16:39:14,745 - mmtrack - INFO - load detector from: https://download.openmmlab.com/mmtracking/mot/faster_rcnn/faster-rcnn_r50_fpn_4e_mot17-ffa52ae7.pth
[                                                  ] 0/150, elapsed: 0s, ETA:Traceback (most recent call last):
  File "demo/demo_mot.py", line 88, in <module>
    main()
  File "demo/demo_mot.py", line 73, in main
    model.show_result(
  File "/mnt/data1/mmtracking/mmtrack/models/mot/base.py", line 267, in show_result
    img = imshow_tracks(
  File "/mnt/data1/mmtracking/mmtrack/core/utils/visualization.py", line 23, in imshow_tracks
    return _cv2_show_tracks(*args, **kwargs)
  File "/mnt/data1/mmtracking/mmtrack/core/utils/visualization.py", line 44, in _cv2_show_tracks
    assert bboxes.shape[1] == 5
AssertionError

Can anyone be kind to tell me how to solve this problem? Thanks very much.

**Comment by OceanPang** [comment]
Hi @btdan, this is because there is no output bounding box on your video, I will update the code to adapt this case.

**Comment by OceanPang** [comment]
@btdan fixed in #86, you can have a try again.

**Comment by btdan** [comment]
After I modify the code follow your conduction, this program works very well. Thanks very much.
