### ISSUE TITLE
Runtimeerror in inference of MOT tracktor

### ISSUE THREAD

**Issue by MotiBaadror** [open-mmlab/mmtracking#869]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
A clear and concise description of what the bug is:
 I am getting below error while running inference on the custom model I trained 
```
Warning: The model doesn't have classes
[                                                  ] 1/472, 0.4 task/s, elapsed: 3s, ETA:  1295sTraceback (most recent call last):
  File "d:/Research/mm/mmtracking/demo/infer_mot.py", line 14, in <module>
    result = inference_mot(mot_model, img, frame_id=i)
  File "C:\Users\MotiRam\Anaconda3\envs\openmmlab\lib\site-packages\mmtrack\apis\inference.py", line 122, in inference_mot 
    result = model(return_loss=False, rescale=True, **data)
  File "C:\Users\MotiRam\Anaconda3\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl  
    return forward_call(*input, **kwargs)
  File "C:\Users\MotiRam\Anaconda3\envs\openmmlab\lib\site-packages\mmcv\runner\fp16_utils.py", line 119, in new_func      
    return old_func(*args, **kwargs)
  File "C:\Users\MotiRam\Anaconda3\envs\openmmlab\lib\site-packages\mmtrack\models\mot\base.py", line 136, in forward      
    return self.forward_test(img, img_metas, **kwargs)
  File "C:\Users\MotiRam\Anaconda3\envs\openmmlab\lib\site-packages\mmtrack\models\mot\base.py", line 113, in forward_test 
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "C:\Users\MotiRam\Anaconda3\envs\openmmlab\lib\site-packages\mmtrack\models\mot\tracktor.py", line 135, in simple_test
    track_bboxes, track_labels, track_ids = self.tracker.track(
  File "C:\Users\MotiRam\Anaconda3\envs\openmmlab\lib\site-packages\mmcv\runner\fp16_utils.py", line 208, in new_func      
    return old_func(*args, **kwargs)
  File "C:\Users\MotiRam\Anaconda3\envs\openmmlab\lib\site-packages\mmtrack\models\trackers\tracktor_tracker.py", line 151, in track
    prop_bboxes, prop_labels, prop_ids = self.regress_tracks(
  File "C:\Users\MotiRam\Anaconda3\envs\openmmlab\lib\site-packages\mmtrack\models\trackers\tracktor_tracker.py", line 78, in regress_tracks
    ids = ids[valid_inds]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

**Reproduction**

1. What command or script did you run?:

```
import mmcv
import tempfile
from mmtrack.apis import inference_mot, init_model
mot_config = 'configs/mot/tracktor/tracktor_faster-rcnn_r50_fpn_8e_mot20-private-half_football.py'
input_video = 'data/fullbodygt21/videos/57583_000082_Endzone.mp4'
imgs = mmcv.VideoReader(input_video)
# build the model from a config file
mot_model = init_model(mot_config, device='cuda:0')
prog_bar = mmcv.ProgressBar(len(imgs))
out_dir = tempfile.TemporaryDirectory()
out_path = out_dir.name
# test and show/save the images
for i, img in enumerate(imgs):
    result = inference_mot(mot_model, img, frame_id=i)
    mot_model.show_result(
            img,
            result,
            show=False,
            wait_time=int(1000. / imgs.fps),
            out_file=f'{out_path}/{i:06d}.jpg')
    prog_bar.update()

output = './demo/57583_000082_Endzone.mp4'
print(f'\n making the output video at {output} with a FPS of {imgs.fps}')
mmcv.frames2video(out_path, output, fps=imgs.fps, fourcc='mp4v')
out_dir.cleanup()
```

```none
A placeholder for the command.
```

3. Did you make any modifications on the code or config? Did you understand what you have modified?: yes, I changed the path for checkpoints

**Comment by MotiBaadror** [comment]
Added a line at at  `mmtrack/api/inference .py`
```
    else:
        for m in model.modules():
            assert not isinstance(
                m, RoIPool
            ), 'CPU inference with RoIPool is not supported currently.'
        # just get the actual data from DataContainer
        data['img_metas'] = data['img_metas'][0].data #to(device)
        **data['img'] = data['img'].to(device)**
```
