### ISSUE TITLE
demo running issue

### ISSUE THREAD

**Issue by GuangWei-Zhang** [open-mmlab/mmtracking#879]
May I know how to modify the __init__.py file to solve the compatibility issue?

(mmtracking) C:\Users\guangwei\mmtracking>python demo/demo_mot_vis.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4
Traceback (most recent call last):
  File "demo/demo_mot_vis.py", line 9, in <module>
    from mmtrack.apis import inference_mot, init_model
  File "c:\users\guangwei\mmtracking\mmtrack\__init__.py", line 5, in <module>
    import mmdet
  File "C:\Users\guangwei\.conda\envs\mmtracking\lib\site-packages\mmdet\__init__.py", line 26, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==2.0.0 is used but incompatible. Please install mmcv>=1.3.8, <=1.5.0.

**Comment by quickmcu** [comment]
pip  install mmcv>=1.3.8 试试
来回测试
