### ISSUE TITLE
unexpected keyword argument 'return_inds' 

### ISSUE THREAD

**Issue by jin-s13** [open-mmlab/mmtracking#88]
**Describe the bug**

An error occurs, when I run demos with tracktor. 

**Reproduction**

1. What command or script did you run?

`python demo/demo_mot.py configs/mot/tracktor/tracktor_faster-rcnn_r50_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot2.mp4 --device cpu`

2. Did you make any modifications on the code or config? 
No. I made no changes.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
sys.platform: darwin
Python: 3.7.4 (default, Aug 13 2019, 15:17:50) [Clang 4.0.1 (tags/RELEASE_401/final)]
CUDA available: False
GCC: Apple clang version 12.0.0 (clang-1200.0.32.28)
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 4.2
  - clang 9.0.0
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - NNPACK is enabled
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -faligned-new -fno-math-errno -fno-trapping-math -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=OFF, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.2.0
MMCV: 1.2.1
mmtrack: 0.5.0
```

**Error traceback**

```none
Downloading: "https://download.openmmlab.com/mmtracking/mot/reid/tracktor_reid_r50_iter25245-a452f51f.pth" to /Users/apple/.cache/torch/checkpoints/tracktor_reid_r50_iter25245-a452f51f.pth
100%|██████████| 98.4M/98.4M [00:11<00:00, 8.75MB/s]
[>>>>                               ] 1/8, 0.1 task/s, elapsed: 9s, ETA:    60sTraceback (most recent call last):
  File "/Users/apple/Desktop/github/mmtracking/demo/demo_mot.py", line 88, in <module>
    main()
  File "/Users/apple/Desktop/github/mmtracking/demo/demo_mot.py", line 64, in main
    result = inference_mot(model, img, frame_id=i)
  File "/Users/apple/Desktop/github/mmtracking/mmtrack/apis/inference.py", line 92, in inference_mot
    result = model(return_loss=False, rescale=True, **data)
  File "/Users/apple/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/apple/anaconda3/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/Users/apple/Desktop/github/mmtracking/mmtrack/models/mot/base.py", line 154, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/Users/apple/Desktop/github/mmtracking/mmtrack/models/mot/base.py", line 131, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/Users/apple/Desktop/github/mmtracking/mmtrack/models/mot/tracktor.py", line 139, in simple_test
    **kwargs)
  File "/Users/apple/Desktop/github/mmtracking/mmtrack/models/mot/trackers/tracktor_tracker.py", line 146, in track
    feats, img_metas, model.detector, frame_id, rescale)
  File "/Users/apple/Desktop/github/mmtracking/mmtrack/models/mot/trackers/tracktor_tracker.py", line 72, in regress_tracks
    return_inds=True)
TypeError: multiclass_nms() got an unexpected keyword argument 'return_inds'

```

**Comment by OceanPang** [comment]
@jin-s13 Please update the version of your mmdet.

**Comment by jin-s13** [comment]
Thanks for the reply. I updated mmdet (mmdet==2.8.0 for now) and it still does not work. The same error.

By the way, the example `deepsort` demo works fine.

**Comment by jin-s13** [comment]
Thanks. I have updated mmdet to the latest vesion. And it works!
