### ISSUE TITLE
prev_img_prefix, prev_img_name = prev_img_meta[ ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by yinxingshu41** [open-mmlab/mmtracking#894]
An error occurred while running mmtracking on the Windows system, and the configuration file is using qdtrack_ Faster rcnn_ R101_ Fpn_ 24e_ Lvis.py, training was conducted on the lvis dataset, with the test set being TAO validation. However, an error occurred while running python tools/test. py: [] 40/36375, 3.7 task/s, delayed: 11s, ETA: 9843sTraceback (most recent call last):

File "E: ComputerVision 8mmtracking mmtracking master tools test. py", line 236, in<module>

Main()

File "E:\\ComputerVision\\mmtracking-master\\tools\\test. py", line 186, in main

Outputs=single_ GPU_ Test（

File "E:\\ComputerVision\\8mmtracking\\mmtracking\\master\\mmtrack\\apis\\test. py", line 84, in single_ GPU_ Test

Prev_ Img_ Prefix_ Img_ Name=prev_ Img_ Meta[

ValueError: not enough values to unpack (expected 2, got 1).

This error appears in the 40th image. How can I resolve it?

**Comment by jangbi1** [comment]
I have same errors. Do you solve it?
