### ISSUE TITLE
Error in running demo 

### ISSUE THREAD

**Issue by nyanmn** [open-mmlab/mmtracking#905]
I have installed mmtrack.
```
mmcv version is 1.7.1
mmdet version is 2.28.0
mmtrack version is 0.14.0.
```
When run demo command as 
`python demo/demo_mot_vis.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4`

I have errors as

```
/home/atic/anaconda3/envs/open-mmtrack/lib/python3.7/site-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
Traceback (most recent call last):
  File "demo/demo_mot_vis.py", line 9, in <module>
    from mmtrack.apis import inference_mot, init_model
  File "/home/atic/mmtracking/mmtrack/apis/__init__.py", line 2, in <module>
    from .inference import inference_mot, inference_sot, inference_vid, init_model
  File "/home/atic/mmtracking/mmtrack/apis/inference.py", line 14, in <module>
    from mmtrack.models import build_model
  File "/home/atic/mmtracking/mmtrack/models/__init__.py", line 3, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/atic/mmtracking/mmtrack/models/backbones/__init__.py", line 2, in <module>
    from .mixformer_backbone import ConvVisionTransformer
  File "/home/atic/mmtracking/mmtrack/models/backbones/mixformer_backbone.py", line 9, in <module>
    from einops import rearrange
  File "/home/atic/anaconda3/envs/open-mmtrack/lib/python3.7/site-packages/einops-0.7.0rc2-py3.7.egg/einops/__init__.py", line 14, in <module>
    from .einops import rearrange, reduce, repeat, einsum, parse_shape, asnumpy
  File "/home/atic/anaconda3/envs/open-mmtrack/lib/python3.7/site-packages/einops-0.7.0rc2-py3.7.egg/einops/einops.py", line 807
    def einsum(tensor: Tensor, pattern: str, /) -> Tensor:
                                             ^
SyntaxError: invalid syntax
free(): invalid pointer
Aborted (core dumped)

```

What is wrong with the errors?

**Comment by nyanmn** [comment]
The problem is solved. einsum is uninstalled and installed.
