### ISSUE TITLE
KeyError: 'detections'

### ISSUE THREAD

**Issue by yangxiaoyany** [open-mmlab/mmtracking#91]
hello,I  met an error when i test the demo.mp4 .Thank  you for helping me to solve it.

(mmdet) yxy@yxy:/media/yxy/4TB/ayxy/mmtracking$ python demo/demo_mot.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-public-half.py --input demo/demo.mp4 --output mot.mp4
2021-01-13 21:36:14,270 - mmtrack - INFO - load detector from: https://download.openmmlab.com/mmtracking/mot/faster_rcnn/faster-rcnn_r50_fpn_4e_mot17-half-64ee2ed4.pth
[                                                  ] 0/8, elapsed: 0s, ETA:Traceback (most recent call last):
  File "demo/demo_mot.py", line 88, in <module>
    main()
  File "demo/demo_mot.py", line 64, in main
    result = inference_mot(model, img, frame_id=i)
  File "/media/yxy/4TB/ayxy/mmtracking/mmtrack/apis/inference.py", line 78, in inference_mot
    data = test_pipeline(data)
  File "/media/yxy/4TB/ayxy/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/media/yxy/4TB/ayxy/mmtracking/mmtrack/datasets/pipelines/loading.py", line 100, in __call__
    detections = results['detections']

**KeyError: 'detections'**

**Comment by GT9505** [comment]
The config you used (`sort_faster-rcnn_fpn_4e_mot17-public-half.py`) needs external detections like public detections in MOT17 challenge. Please use config with private detections (e.g `sort_faster-rcnn_fpn_4e_mot17-private-half.py`) to run `demo_mot.py`

**Comment by yangxiaoyany** [comment]
Thank  you.it works
