### ISSUE TITLE
Compatability Issue between MMCV and MMTracking

### ISSUE THREAD

**Issue by ShenZheng2000** [open-mmlab/mmtracking#932]
I spend quite a lot time to install the correct mmcv and mmtrack version so I can successully install mmtrack. However, even after that, the demo code is unsuccessful. 

Here are my mm-related package versions
```
mmtrack==0.14.0
mmdet==2.19.1
mmcv==1.3.17
```

Here is my torch-related package installations
```
pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
```

And here is my error
```
root@sjc12adashpcp03:/home/szheng/Traffic_Light/Methods/mmtracking# python demo/demo_mot_vis.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4
/usr/local/lib/python3.8/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "demo/demo_mot_vis.py", line 9, in <module>
    from mmtrack.apis import inference_mot, init_model
  File "/home/szheng/Traffic_Light/Methods/mmtracking/mmtrack/apis/__init__.py", line 2, in <module>
    from .inference import inference_mot, inference_sot, inference_vid, init_model
  File "/home/szheng/Traffic_Light/Methods/mmtracking/mmtrack/apis/inference.py", line 14, in <module>
    from mmtrack.models import build_model
  File "/home/szheng/Traffic_Light/Methods/mmtracking/mmtrack/models/__init__.py", line 10, in <module>
    from .reid import *  # noqa: F401,F403
  File "/home/szheng/Traffic_Light/Methods/mmtracking/mmtrack/models/reid/__init__.py", line 2, in <module>
    from .base_reid import BaseReID
  File "/home/szheng/Traffic_Light/Methods/mmtracking/mmtrack/models/reid/base_reid.py", line 2, in <module>
    from mmcls.models import ImageClassifier
  File "/usr/local/lib/python3.8/dist-packages/mmcls/__init__.py", line 55, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.3.17 is used but incompatible. Please install mmcv>=1.4.2, <=1.9.0.
```

Please solve this issue as soon as possible.

**Comment by ShenZheng2000** [comment]
I have solved the problem with the following package versions. I will close the issue for now. 

```
mmtrack==0.14.0
mmdet==2.26.0
mmcv-full==1.7.0
torch==1.8.0+cu111
torchvision==0.9.0+cu111
torchaudio==0.8.0
```
