### ISSUE TITLE
python setup.py develop

### ISSUE THREAD

**Issue by AAABAB** [open-mmlab/mmtracking#98]
root@/mmtracking-master# python setup.py develop
running develop
running egg_info
writing mmtrack.egg-info/PKG-INFO
writing dependency_links to mmtrack.egg-info/dependency_links.txt
writing requirements to mmtrack.egg-info/requires.txt
writing top-level names to mmtrack.egg-info/top_level.txt
reading manifest file 'mmtrack.egg-info/SOURCES.txt'
writing manifest file 'mmtrack.egg-info/SOURCES.txt'
/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py:339: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
running build_ext
Creating /opt/conda/lib/python3.6/site-packages/mmtrack.egg-link (link to .)
mmtrack 0.5.0 is already the active version in easy-install.pth

Installed /data/lyy/object-detection/mmtracking-master
Processing dependencies for mmtrack==0.5.0
Searching for dotty_dict
Reading https://pypi.org/simple/dotty_dict/
Downloading https://files.pythonhosted.org/packages/a7/da/fc25898c4edb9549b2aac0f7329fec027d654e94d4c4b89849d4c5fff0a4/dotty_dict-1.3.0.tar.gz#sha256=eb0035a3629ecd84397a68f1f42f1e94abd1c34577a19cd3eacad331ee7cbaf0
Best match: dotty-dict 1.3.0
Processing dotty_dict-1.3.0.tar.gz
Writing /tmp/easy_install-6tvk0j52/dotty_dict-1.3.0/setup.cfg
Running dotty_dict-1.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6tvk0j52/dotty_dict-1.3.0/egg-dist-tmp-2m_gtven
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/opt/conda/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/opt/conda/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-6tvk0j52/dotty_dict-1.3.0/setup.py", line 16, in <module>
    
  File "/opt/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 118: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 159, in <module>
    zip_safe=False)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/opt/conda/lib/python3.6/site-packages/setuptools/command/develop.py", line 155, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 759, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 781, in resolve
    replace_conflicting=replace_conflicting
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1064, in best_match
    return self.obtain(req, installer)
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1076, in obtain
    return installer(requirement)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 686, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 712, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 897, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1167, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1151, in run_setup
    run_setup(setup_script, args)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/opt/conda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/opt/conda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/opt/conda/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/opt/conda/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/opt/conda/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-6tvk0j52/dotty_dict-1.3.0/setup.py", line 16, in <module>
    
  File "/opt/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 118: ordinal not in range(128)

**Comment by OceanPang** [comment]
It seems that the bug appears when installing `dotty-dict`.

Can you try to `pip install dotty-dict` independently and see what happens here?

**Comment by ZilongZhang32** [comment]
I tried to install MMTracking on **Windows 10** for some reason, and the first five steps went well.
But I had the same problem with AAABAB when I ran step 6 `python setup.py develop`, the output is very similiar to AAABAB's.
After that, I tried `pip install dotty-dict` and still failed to install it:

The output of `pip install dotty-dict`:
```shell
(mmlab) C:\Users\xxx> pip install dotty_dict
Collecting dotty_dict
  Using cached dotty_dict-1.3.0.tar.gz (32 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\xxx\anaconda3\envs\mmlab\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-aw4pcd6b\\dotty-dict_bceb15a1a68e4c15a0f401aa1a1cb68e\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-aw4pcd6b\\dotty-dict_bceb15a1a68e4c15a0f401aa1a1cb68e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xxx\AppData\Local\Temp\pip-pip-egg-info-j0z8v54o'
         cwd: C:\Users\xxx\AppData\Local\Temp\pip-install-aw4pcd6b\dotty-dict_bceb15a1a68e4c15a0f401aa1a1cb68e\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxx\AppData\Local\Temp\pip-install-aw4pcd6b\dotty-dict_bceb15a1a68e4c15a0f401aa1a1cb68e\setup.py", line 16, in <module>
        readme = readme_file.read()
    UnicodeDecodeError: 'cp950' codec can't decode byte 0xc5 in position 118: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I don't know how to fix this. Does the operating system matter?

**Comment by PaulKlinger** [comment]
In case anyone else stumbles over this:
The issue is that the default encoding is set to ascii, and it's trying to read a utf-8 file. Setting the environment variables
`LANG=C.UTF-8 LC_ALL=C.UTF-8`
fixes it.
